### PR TITLE
PS-7727 Add information for keyring components to data at rest docs (…

### PR DESCRIPTION
**Pull request by patrickbirch**
…8.0)

 Changes to be committed:
	modified:   source/index.rst
	modified:   source/security/using-keyring-plugin.rst

### CODE REVIEW

**Comment by altmannmarcelo** [comment]
@patrickbirch which current URL is this doc from ?

**Comment by patrickbirch** [comment]
Sent the doc link in Slack.

**Review by altmannmarcelo — APPROVED** [review]
LGTM

**Review by alina-derkach-oaza — APPROVED** [review]
LGTM

**Review by nastena1606 — APPROVED** [review]
LGTM

**Comment by patrickbirch** [comment]
This pull request is closed because the documentation has been moved to a different repository.

**Pull request closed without merging**
