### PR TITLE
Fix lp:1663452 "Resource allocation failures in 'CREATE/DROP COMPRESSION_DICTIONARY' result in server crashes (debug mode) | handle_fatal_signal (sig=6) in innobase_create_zip_dict" (5.7)

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/670/

**Review by laurynas-biveinis — COMMENTED** [review]
Same questions as for 5.6

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/674/

**Review by laurynas-biveinis — APPROVED** [review]
Same comment as for the 5.6 version

**Pull request merged**
