### PR TITLE
Tokudb fast upserts updates gca 5.7

### PR DESCRIPTION
**Pull request by vlad-lesin**
See: https://github.com/percona/percona-server/pull/2098
Testing: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1532/

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.6 (as you update this PR please edit the 5.7 commit message to list any non-trivial changes from the 5.6 version)

**Comment by vlad-lesin** [comment]
New testing: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1652/

**Comment by vlad-lesin** [comment]
Ready for the next review round.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comments as for 5.6 (it might make sense to have the 5.6 PR reviewed to approved state before updating this one)

**Comment by vlad-lesin** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1690

**Comment by vlad-lesin** [comment]
Last changes testing: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1690/
Compilation testing after MY_NODISCARD macros addition: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1710/

**Review by laurynas-biveinis — COMMENTED** [review]
Same question as for 5.6

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
