### PR TITLE
Fixes bug 1602986 in 5.7

### PR DESCRIPTION
**Pull request by gl-sergei**
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/262/

### CODE REVIEW

**Comment by gl-sergei** [comment]
updated: http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/267/

**Comment by gl-sergei** [comment]
@laurynas-biveinis is this one OK to merge? I see that only 5.6 version was approved...

**Comment by laurynas-biveinis** [comment]
@gl-sergei, I thought the the last round of 5.6 changes were not upmerged to 5.7?
LGTM if they are

**Comment by gl-sergei** [comment]
Yes, this version contains commit 7faf441 from 5.6 version.

**Pull request merged**
