### PR TITLE
Merge MySQL 5.6.45

### PR DESCRIPTION
**Pull request by dutow**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Please, update the message for the 3-rd commit (conflicts resolved) with
the link to the merge blueprint
```
https://jira.percona.com/browse/PS-5531
```
Also, add a paragraph about raising versions
```
***
VERSION raised to "5.6.45-86.1".
univ.i version raised to "86.1".
```
(this helps our build team)

**Comment by percona-ysorokin** [comment]
Also, put a note into https://jira.percona.com/browse/PS-4513 comments that this issue was fixed in upstream 5.6.46.

**Review by laurynas-biveinis — COMMENTED** [review]
What is the status of testcase for bug 88636?

**Comment by dutow** [comment]
That was caused by errors in the utf8 incorrect character handling logic. Upstream added both unit tests and string handling related mtr tests.

**Comment by dutow** [comment]
https://ps56.cd.percona.com/job/percona-server-5.6-param/29/

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by dutow** [comment]
@percona-ysorokin I've edited the commit message

**Comment by percona-ysorokin** [comment]
@dutow Thanks

I also noticed that among ssl-related failures on Jenkins there is also a `Lost connection to MySQL server during query` (most probably a crash) in 'rpl.rpl_get_master_version_and_clock' on CentOS 7, Debug
https://ps56.cd.percona.com/job/percona-server-5.6-pipeline/2630/consoleText

```
rpl.rpl_get_master_version_and_clock 'mix' w1 [ fail ]  Found warnings/errors in server log file!
        Test ended at 2019-07-30 13:37:08
line
2019-07-30 16:36:53 6857 [Warning] Slave I/O: SET @master_heartbeat_period to master failed with error: Lost connection to MySQL server during query, Error_code: 2013
^ Found warnings in /tmp/results/PS/mysql-test/var/1/log/mysqld.2.err
ok
```

**Comment by dutow** [comment]
I can't reproduce it locally, and it's also just unstable on jenkins, the next run completed without issues: https://ps56.cd.percona.com/job/percona-server-5.6-param/30/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
