### PR TITLE
Procfs fixes

### PR DESCRIPTION
**Pull request by avbelov23**
See commits for more information

### CODE REVIEW

**Comment by george-lorch** [comment]
https://ps80.cd.percona.com/view/8.0/job/percona-server-8.0-param/1032/

**Comment by avbelov23** [comment]
@georgelorchpercona, 
>https://ps80.cd.percona.com/view/8.0/job/percona-server-8.0-param/1032/
Access Denied
avbelov23 is missing the Overall/Read permission

**Comment by george-lorch** [comment]
Changes look good, CI tested out OK, but, it looks like something changed on the release branch (force push or squash perhaps).  @oleksandr-kachan for the PS 8.0.26 release, can you cherry-pick the four ProcFS related patches from August 4th in this PR over to the release branch?

**Comment by george-lorch** [comment]
Thanks for the rebase @avbelov23, that helps, unfortunately though, I can not easily give you access to that jenkins job right now.  @oleksandr-kachan now we only need to merge it instead of cherry-pick when you have the release branch in good shape.

**Pull request merged**
