### PR TITLE
PS-5550 : RHEL8 runners in 5.7 seem to be missing python

### PR DESCRIPTION
**Pull request by george-lorch**
- Changed TokuDB test generator makefiles to invoke python2 explicitly rather
  than generic python.
- Changed TokuDB *.py scripts to she-bang with python2 instead of python.

### CODE REVIEW

**Comment by george-lorch** [comment]
No jenkins as these changes are not run as part of any mtr suite, only to python scripts that are used to generate mtr tests.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Please take a look at innodb_stress suite too, it's even more acute (here we have test generators whereas there it's tests themselves)

**Comment by george-lorch** [comment]
> Please take a look at innodb_stress suite too, it's even more acute (here we have test generators whereas there it's tests themselves)

Ack, yes, we discussed this and it slipped my mind while backporting to 5.6 and re-creating work based on GCA.  Will get these touched up and jenkins-ized if possible.

**Comment by george-lorch** [comment]
OK, got the innodb_stress suite changes and a jenkins of just the innodb_stress suite run https://ps56.cd.percona.com/job/percona-server-5.6-param/7/ with what appear to be spurious failures unrelated to this change.

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
