### PR TITLE
Merge upstream 5.6.35 into Percona Server

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Jenkins run?

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1582/
Something strange is going on on CentOS 5 x64. The problem appears only on Jenkins slaves. Local builds work fine. Still investigating.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
You have to update tokudb.rpl.rpl_extra_col_slave_tokudb.

Then, things like

worker[3] mysql-test-run: WARNING: Process [mysqld.3 - pid: 17924, winpid: 17924, exit: 256] died after mysql-test-run waited 2.7 seconds for /mnt/workspace/percona-server-5.6-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/build/mysql-test/var/3/run/mysqld.3.pid to be created.
rpl.rpl_row_img_eng_noblob 'row'         w3 [ fail ]
...
2017-01-05 02:43:23 17925 [ERROR] Can't start server: Bind on TCP/IP port: Address already in use
2017-01-05 02:43:23 17925 [ERROR] Do you already have another mysqld server running on port: 13023 ?
2017-01-05 02:43:23 17925 [ERROR] Aborting

probably go to JEN-546.

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link with 'tokudb.rpl.rpl_extra_col_slave_tokudb' fixed
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1585/

**Comment by laurynas-biveinis** [comment]
What is the status of CentOS 5?

unittest/gunit/CMakeFiles/merge_large_tests-t.dir/build.make:201: *** target pattern contains no `%'.  Stop.
make[1]: *** [unittest/gunit/CMakeFiles/merge_large_tests-t.dir/all] Error 2

**Comment by laurynas-biveinis** [comment]
Same error on Wheezy (but only in Release config):

unittest/gunit/CMakeFiles/merge_large_tests-t.dir/build.make:201: *** target pattern contains no `%'.  Stop.
make[1]: *** [unittest/gunit/CMakeFiles/merge_large_tests-t.dir/all] Error 2

**Comment by percona-ysorokin** [comment]
Fixed problem with cmake downloading 'googletest-release-1.8.0.zip' on some platforms.
As a workaround, Google Test package is downloaded manually using 'wget' just before running 'cmake'.
Updated Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1587/

**Comment by laurynas-biveinis** [comment]
LGTM, but what does the download issue mean for users? Will it fail for them? Does it need to be logged somewhere besides having a workaround in Jenkins?

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
