### PR TITLE
General spelling fixes in comments in Innobase/Xtradb and TokuDB

### PR DESCRIPTION
**Pull request by ottok**
Contribution released with the BSD 2-clause license and thus available for
any MySQL variant to use freely.

Copyright (c) 2016 Otto Kekäläinen / The MariaDB Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Signed-off-by: Otto Kekäläinen otto@mariadb.org

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
This is a correct patch, but none of the fixes under storage/innodb are in the XtraDB diff to InnoDB, i.e. no typos introduced by us. Thus, if we merged the InnoDB part, we'd get an upstream diff increase and associated maintenance cost. Oracle should merge this, not us.

Co-assigning to @georgelorchpercona for storage/tokudb.

**Comment by ottok** [comment]
Ok, I see. I split this PR now into a new branch https://github.com/ottok/percona-server/tree/fix-spelling-oracle and force pushed only the TokuDB part to this PR. Not much left though...

**Comment by ottok** [comment]
Can you merge this please?

**Comment by laurynas-biveinis** [comment]
LGTM. @georgelorchpercona ?

**Review by george-lorch — APPROVED** [review]

**Pull request merged**
