### PR TITLE
Null merge branch 5.6 (commit 90e152c) into 5.7

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/922/

**Comment by laurynas-biveinis** [comment]
Why the diff is not empty?

**Comment by percona-ysorokin** [comment]
I just spotted some discrepancies between 5.6 and 5.7 fix for lp:1669005 "Valgrind error on tokudb.backup.tokudb_backup_exclude"
(https://bugs.launchpad.net/percona-server/+bug/1669005)

**Comment by george-lorch** [comment]
I have the same question as Laurynas, why is the diff not empty? A NULL merge should be truely empty...although, that might be the result of a cherry pick merge of the fix between 5.6 and 5.7.

**Comment by percona-ysorokin** [comment]
@georgelorch 
Here are 2 fixes for the same lp:1669005 "Valgrind error on tokudb.backup.tokudb_backup_exclude" from Vlad
5.6: https://github.com/percona/percona-server/pull/1608/commits/e2307312e52c62d499387efc1e829a25cf9bbfde
5.7: https://github.com/percona/percona-server/pull/1609/commits/c92307809fe5b5b7fc77db7db0390d40dfe4ced6 (cherry-picked from e230731)

My non-null part (commit https://github.com/percona/percona-server/pull/1728/commits/59e9f3b42de070dda751fcdb1cd3f892e2fa2386) just adds `&& mi->host != 0` before `mi->host[0])` conditions, which I believe were dropped by mistake.

**Review by george-lorch — APPROVED** [review]
Discussing the changes w/ Yura it seems that there was a commit cherry-picked from 5.6 to 5.7 that was incomplete and lost the addition of several "&& mi->host[0]" in the tokudb backup plugin. Yura could have written an issue and the code could have been re-introduced as a separate commit, but instead it was added as part of this null merge. I don't have an issue with it as long as we understand now why a null merge actually has a code change.

So this null merge moves the 5.6 GCA point to this commit:

commit 90e152c54562ab51cc0425c22c6efa78734a954a
Merge: 343f7e0 30743d5
Author: Laurynas Biveinis <laurynas.biveinis@gmail.com>
Date:   Mon Apr 24 09:59:34 2017 -0700

    Merge pull request #1679 from laurynas-biveinis/bug1659224-5.6
    
    Fix bug 1659224 (Test main.status is unstable)


This seems much better GCA point than we had before but still seems a little behind. Approving.

**Pull request merged**
