### PR TITLE
[BLD-893] mysqld_safe in 5.7 does not restart the server when it is killed

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Comment by laurynas-biveinis** [comment]
There's an MTR test for mysqld_safe. Has it been checked?

**Comment by EvgeniyPatlan** [comment]
Sure.
Here it is:

worker[1] > Adding mysqld-debug first in list of binaries to look for
worker[1] > Started [mysqld.1 - pid: 32002, winpid: 32002]
worker[1] > Got [mysqltest - pid: 30800, winpid: 30800, exit: 0]
worker[1] > Started [warnings-mysqld.1 - pid: 32030, winpid: 32030]
worker[1] Got [warnings-mysqld.1 - pid: 32030, winpid: 32030, exit: 15872]
worker[1] Started [check-mysqld_1 - pid: 32032, winpid: 32032]
worker[1] Got [check-mysqld_1 - pid: 32032, winpid: 32032, exit: 0]
worker[1] main.mysqld_safe                         worker[1] [ pass ]  10670
main.mysqld_safe                         [ pass ]  10670
worker[1] Server said BYE
worker[1] > Stopping all servers...
> Child closed socket
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 10.670 of 17 seconds executing testcases

Completed: All 1 tests were successful.

**Comment by laurynas-biveinis** [comment]
This might have caused https://bugs.launchpad.net/percona-server/+bug/1738742, @EvgeniyPatlan, please check?

**Pull request merged**
