### PR TITLE
Bug 1435099: Audit Log events do not report default DB (5.7)

### PR DESCRIPTION
**Pull request by gl-sergei**

### CODE REVIEW

**Comment by gl-sergei** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/242/

**Comment by gl-sergei** [comment]
There is a bug in 5.7 because of which `mysql_change_user` doesn't change default db in audit plugin. https://bugs.mysql.com/?id=82118

**Comment by gl-sergei** [comment]
Jenkins build updated:
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/249/

**Comment by gl-sergei** [comment]
Branch updated.
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/257/

**Comment by laurynas-biveinis** [comment]
LGTM

**Pull request merged**
