### PR TITLE
Ps 5.7 4386

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1904/

**Comment by george-lorch** [comment]
new jenkins https://ps.cd.percona.com/job/percona-server-5.7-param/41/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comment as for the 5.6 version

**Comment by george-lorch** [comment]
Fixed and new jenkins https://ps.cd.percona.com/job/percona-server-5.7-param/47/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
