### PR TITLE
PS-6788: Merge MySQL 5.7.30 part 2

### PR DESCRIPTION
**Pull request by inikep**
https://jira.percona.com/browse/PS-6788
***
Updated man pages from MySQL Server 5.7.30 source tarball.
***
Updated `scripts/fill_help_tables.sql` from MySQL Server 5.7.30 source tarball.   
***
VERSION raised to "5.7.30-33".
PERCONA_INNODB_VERSION in univ.i raised to "33".   
***
Fixed `main.partition_debug`, `innodb.xtradb_compressed_columns_debug`, `rocksdb.type_json`, `rocksdb_rpl.rpl_rocksdb_row_alter_table_drop_index_slave`, `rpl.rpl_create_drop_temp_table_slave_binlog_off`, `rpl.rpl_backup_locks_mts`, `rpl.percona_bug1358836`, `binlog_encryption.binlog_encryption_on_while_binlog_off`, `binlog_encryption.percona_system_key_rotation`
***
Improved `innodb.bug76142` MTR test.
***
Fix macOS compilation issues with `client/mysql.cc`. 
***
Fix Valgrind issue with `mysqldump_gtid_purged`
***
Suppress warnings for gcc ASan build with `storage/rocksdb/rocksdb/util/bloom.cc`
***
Ported PS-7020: convert MTR tests from python2 to python3
1. Fix failing `rocksdb_stress.rocksdb_stress`
2. Convert `python2` scripts to support both `python2` and `python3`

Current requirements to run these scripts are: 
a) python2.6+ (because of `from __future__ import print_function`) 
b) `python` linked to either `python2` or `python3`

### CODE REVIEW

**Comment by inikep** [comment]
Tested at:
`--big-test` at https://ps57.cd.percona.com/job/percona-server-5.7-param/267
`--big-test --sanitize -DWITH_ASAN=ON -DWITH_ASAN_SCOPE=ON` at https://ps57.cd.percona.com/job/percona-server-5.7-asan-param/15
`--big-test --valgrind -DWITH_VALGRIND=ON` at https://ps57.cd.percona.com/job/percona-server-5.7-valgrind-param/12

**Comment by inikep** [comment]
Tested at https://ps57.cd.percona.com/job/percona-server-5.7-param/270/

**Comment by inikep** [comment]
Tested at https://ps57.cd.percona.com/job/percona-server-5.7-param/273/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
