### PR TITLE
Ps 5.7 db 720

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/54/

**Comment by laurynas-biveinis** [comment]
Same comment as for the 5.6 version of this PR + please confirm that the changed TokuDB tests pass locally (until Jenkins has 5.7 TokuDB testing)

**Comment by laurynas-biveinis** [comment]
5.7 should also drop +#ifdef WITH_PARTITION_STORAGE_ENGINE, it has been removed in the rest of core server

**Comment by george-lorch** [comment]
I had wondered about the WITH_PARTITION_STORAGE_ENGINE in 5.7 when I merged, so I searched in sql_table.cc to see if there were other occurrences or if it maybe had changed for some reason due to native partitioning and saw that there were still #ifdef WITH_PARTITIONED_STORAGE_ENGINE in there, so I assumed it was still valid. Since I need to add to the mtr tests I'll go ahead and remove it when I re-merge.

**Comment by laurynas-biveinis** [comment]
It is other Percona patches that upmerged WITH_PARTITION_STORAGE_ENGINE that show up in grep now :) I have on my TODO to clean them up. And the symbol is still valid as a CMake variable.

**Comment by george-lorch** [comment]
RE 5.7 mtr passing, yes, I do run not only the individual tests but full PS and PS + TokuDB suites locally...due to the still numerous failures in TokuDB 5.7 MTR it takes a little time to sift through the results looking for possible regressions when comparing to the large number of currently known failures.

**Comment by george-lorch** [comment]
Re-merged expanded tests, re-recorded, removed #ifdef as discussed, and push --force the branch.

jenkins not re-run due to current backlog in running jobs, full mtr run locally and completes as expected. If jenkins clears up before merging, I'll fire another job.

**Comment by george-lorch** [comment]
jenkins pending : http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/57/

**Comment by laurynas-biveinis** [comment]
LGTM

**Comment by george-lorch** [comment]
Rebased to new GCA, re-corrected merge diffs and retested locally.

**Pull request merged**
