### PR TITLE
Bug1525407 5.7

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
http://jenkins.percona.com/job/mysql-5.7-param/251/

### CODE REVIEW

**Comment by george-lorch** [comment]
LGTM

**Comment by percona-ysorokin** [comment]
LGTM, only minor comments from 5.5

**Comment by laurynas-biveinis** [comment]
http://jenkins.percona.com/job/mysql-5.7-param/256/

**Comment by percona-ysorokin** [comment]
LGTM

**Pull request merged**
