### PR TITLE
Merge branch '5.5-ps-bug728082' into 5.6-ps-bug728082

### PR DESCRIPTION
**Pull request by ihanick**
http://jenkins.percona.com/job/percona-server-5.6-param/1478/

Merging https://bugs.launchpad.net/percona-server/+bug/728082 fix to 5.6
5.5: https://github.com/percona/percona-server/pull/1135

### CODE REVIEW

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by ihanick** [comment]
http://jenkins.percona.com/job/percona-server-5.6-param/1479/
- merge update for threadpool-related changes

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as 5.5

**Comment by ihanick** [comment]
http://jenkins.percona.com/job/percona-server-5.6-param/1482/
- merge with -master.opt change

**Comment by ihanick** [comment]
http://jenkins.percona.com/job/percona-server-5.6-param/1487/
merge with 5.5 test split

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
