### PR TITLE
Version number of 5.6.29 is mentioned as 5.6.27 in the release notes

### PR DESCRIPTION
**Pull request by grypyrg**
Version number of 5.6.29 is mentioned as 5.6.27.

Reported by Jeremy Tinley.

### CODE REVIEW

**Comment by hrvojem** [comment]
Needs null merge to 5.7 in order to be merged

**Comment by laurynas-biveinis** [comment]
@hrvojem, it's probably too much to require from non-core contributors to learn the GCA process - maybe you can just piggyback the typo fix on the next 5.6 doc change you do?

**Comment by hrvojem** [comment]
@laurynas-biveinis yep that was the plan. I'll fix this with the upcoming releases

**Comment by hrvojem** [comment]
Closing this because it was fixed in different PR which follow the GCA process.

**Pull request closed without merging**
