### PR TITLE
Null-merge branch '5.5' (commit fe5fdaa) into 5.6

### PR DESCRIPTION
**Pull request by percona-ysorokin**
Null merge after upstream 5.5.54 and 5.6.35 merges.

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link (MTR_ARGS=rpl.rpl_init_slave_errors)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/618/

**Comment by laurynas-biveinis** [comment]
What are 430da1a and 8f26be5?

**Comment by percona-ysorokin** [comment]
I messed something up with my local repository, with 5.6 branch in particular. Good you spotted it.

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link after the fix
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/619/

**Comment by laurynas-biveinis** [comment]
@percona-ysorokin, 5.7 job link for a 5.6 PR?

**Review by laurynas-biveinis — APPROVED** [review]
Approved if Jenkins OK

**Comment by percona-ysorokin** [comment]
5.6 build
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1619/

**Pull request merged**
