### PR TITLE
Ps 5.7 tdb 130

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1753/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comments as for 5.6, and

5.7 needs to consider the new HA_CREATE_USED values (HA_CREATE_USED_TABLASPACE, HA_CREATE_USED_COMPRESS)

**Comment by george-lorch** [comment]
Added checking for TABLESPACE and COMPRESS along with updates mtr test to cover. New jenkins https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1757/

**Comment by george-lorch** [comment]
Gah, bad jenkins run.... here's a new one https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1760/

**Review by laurynas-biveinis — APPROVED** [review]
Same as for 5.6

**Pull request merged**
