### PR TITLE
PS-8722: 5.7.42 merge

### PR DESCRIPTION
**Pull request by dutow**
Merge in one PR, as the 5.7 head is properly null merged to the 8.0 branch.

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
@dutow 
`main.mysqldump_single_trans_min_privs` fails with the following error
(Ubuntu 22.04 Jammy, RelWithDebInfo, gcc-12)
```
[ 46%] main.mysqldump_single_trans_min_privs    w11 [ fail ]
        Test ended at 2023-05-02 17:28:02

CURRENT_TEST: main.mysqldump_single_trans_min_privs
Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events.
mysqltest: At line 37: command "$MYSQL_DUMP bug_test -utest --single-transaction --no-tablespaces> $mysqldumpfile" succeeded - should have failed with errno 2...
```

**Comment by dutow** [comment]
@percona-ysorokin Originally I removed that test, but used `rm` instead of `git rm`, so it was still visible in the PR, as it's part of the recent upstream changes I reverted.

Now I instead updated it to work with our version - I don't think keeping it adds too much, but it doesn't take too much time.

**Comment by VarunNagaraju** [comment]
Hi @dutow, 
Have you checked the test mysqldump_gtid_state? It seems to fail with a warning.
```
worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
[ 50%] main.mysqldump_gtid_state                [ fail ]  Found warnings/errors in server log file!
        Test ended at 2023-05-03 11:44:33
line
2023-05-03T06:14:21.253949Z 6 [ERROR] InnoDB: Table `mysql`.`innodb_index_stats` not found.
^ Found warnings in /home/varun/percona-server-5.7/dutow/bld/mysql-test/var/log/mysqld.1.err
ok
```
But, it also fails on 5.7 Head. Perhaps, it is nice to fix here?

```
diff --git a/mysql-test/r/mysqldump_gtid_state.result b/mysql-test/r/mysqldump_gtid_state.result
index 4cf3e7c7e64..0e0addd6de0 100644
--- a/mysql-test/r/mysqldump_gtid_state.result
+++ b/mysql-test/r/mysqldump_gtid_state.result
@@ -55,6 +55,7 @@ MASTER_UUID   1       7
 MASTER_UUID    8       10
 include/assert.inc [GTID_EXECUTED is correct after the restart]
 CALL mtr.add_suppression(".*InnoDB: Table `mysql`.`innodb_table_stats` not found.*");
+CALL mtr.add_suppression(".*InnoDB: Table `mysql`.`innodb_index_stats` not found.*");
 SHOW CREATE TABLE `mysql`.`innodb_table_stats`;
 Table  Create Table
 innodb_table_stats     CREATE TABLE `innodb_table_stats` (
diff --git a/mysql-test/t/mysqldump_gtid_state.test b/mysql-test/t/mysqldump_gtid_state.test
index e8537474f21..77a7f8eb428 100644
--- a/mysql-test/t/mysqldump_gtid_state.test
+++ b/mysql-test/t/mysqldump_gtid_state.test
@@ -104,6 +104,7 @@ SELECT * FROM mysql.gtid_executed;
 --source include/assert.inc
 
 CALL mtr.add_suppression(".*InnoDB: Table `mysql`.`innodb_table_stats` not found.*");
+CALL mtr.add_suppression(".*InnoDB: Table `mysql`.`innodb_index_stats` not found.*");
 
 SHOW CREATE TABLE `mysql`.`innodb_table_stats`;
```

**Review by VarunNagaraju — APPROVED** [review]

**Comment by dutow** [comment]
@VarunNagaraju I'd like to keep this pull request only about the merge. I'm open to fixing existing failures, even for the .42 release branch, but in a separate PR to keep it cleaner.

**Pull request merged**
