### PR TITLE
PS-8327 ALTER TABLE ... CHECK PARTITION inside stored procedure causes problem

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PS-8327
GCA from https://github.com/percona/percona-server/pull/4839

## How to reproduce

```
CREATE TABLE t1(i INT PRIMARY KEY)
PARTITION BY RANGE (i)
(
  PARTITION p0 VALUES LESS THAN (2),
  PARTITION p1 VALUES LESS THAN (4)
);

DELIMITER $$
CREATE PROCEDURE p1()
BEGIN
  ALTER TABLE t1 CHECK PARTITION p0;
END $$
DELIMITER ;

CALL p1();
```

On 5.7: Get an assertion fail on the client on the next command entering:

`sql/net_serv.cc:234: void net_clear(NET*, my_bool): Assertion '!check_buffer || (vio_pending(net->vio) <= 1)' failed`

On 8.0: Client reconnecting on the next command entering.

## Fix

Add `sp_head::MULTI_RESULTS` flag for ALTER TABLE command because it may return a result set in case of CHECK PARTITION.

On 8.0 reconnect was introduced in https://github.com/percona/percona-server/commit/14508bbb179 and assert was removed there: https://github.com/percona/percona-server/commit/14508bbb179#diff-281245ca3dd9f832d0c1cda0cf51f2410801734265ae35e7ae5120d84bd3aeb0L273. But the problem remains the same.

### CODE REVIEW

**Comment by kamil-holubicki** [comment]
https://ps80.cd.percona.com/view/Parallel%20MTR/job/percona-server-8.0-pipeline-parallel-mtr/322/

**Comment by kamil-holubicki** [comment]
@voodam ,
Please check Jenkins run results. It looks like these failures are related
ubuntu-focal.Debug.main.main.sp-error
ubuntu-focal.Debug.main.main.sp_trans

**Comment by voodam** [comment]
> @voodam ,
> Please check Jenkins run results. It looks like these failures are related

@kamil-holubicki Fixed.
Because this fix is also needed for 5.7, I think I need to re-create GCA branch after PR will become aproved.

**Comment by kamil-holubicki** [comment]
https://ps80.cd.percona.com/view/Parallel%20MTR/job/percona-server-8.0-pipeline-parallel-mtr/323/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Comment by voodam** [comment]
> https://ps80.cd.percona.com/view/Parallel%20MTR/job/percona-server-8.0-pipeline-parallel-mtr/323/

@kamil-holubicki, I checked failed tests, they are broken also in parent commit. Squash and merge now (like 5.7 PR)?

**Review by kamil-holubicki — APPROVED** [review]

**Comment by voodam** [comment]
Nothing changed in the code, rebased and formatted only.

**Pull request merged**
