### PR TITLE
Fix lp:1659992 "Function over userstat tables cause mysql to crash" (5.7)

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/742/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.5

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link (as no code changes since the previous commit, just single test run)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/744/

**Review by laurynas-biveinis — APPROVED** [review]

**Review by robgolebiowski — APPROVED** [review]
LGTM

**Pull request merged**
