### PR TITLE
Merge 5.6.29

### PR DESCRIPTION
**Pull request by vlad-lesin**
```
Merge tag 'mysql-5.6.29'

The tests for 74670, 76277 bug fixes are added.

log_slow_applicable() and query_response_time_audit_notify() are fixed to avoid
error of casting from Query_arena* to sp_lex_instr*. The fix is in adding
thd->sp_runtime_ctx check before the casting to be sure we are inside of SP
and thd->stmt_arena can be casted to sp_lex_instr*.

Some replication test results were fixed due to this commit:
907a7cc - Bug#21317739: APPLYING CREATE TEMPORARY TABLE SQL ON A SLAVE
          WITH REPLICATE-REWRITE-DB FAILScommit.
```

http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1082/

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Same comments re. bug 1521120 and the merge blueprint as in the 5.5 merge.

One more comment, as https://blueprints.launchpad.net/percona-server/+spec/merge-5.6.29 says, it should be checked whether testcase for http://bugs.mysql.com/bug.php?id=78292 is there. I am unable to find it (grepping by "no-threads"), if this is correct, can you please add it?

**Comment by laurynas-biveinis** [comment]
Man pages not imported?

**Comment by vlad-lesin** [comment]
> Same comments re. bug 1521120 and the merge blueprint as in the 5.5 merge.

Done.

> One more comment, as https://blueprints.launchpad.net/percona-server/+spec/merge-5.6.29 says, it should be checked whether testcase for http://bugs.mysql.com/bug.php?id=78292 is there. I am unable to find it (grepping by "no-threads"), if this is correct, can you please add it?

Yes, you are right, I missed it. I added the test in perfschema.no_threads.

> Man pages not imported?

Imported now.

**Comment by laurynas-biveinis** [comment]
LGTM

**Comment by laurynas-biveinis** [comment]
threadpool_common.cc:threadpool_remove_connection: should dec_connection_count call be moved after the remove_global_thread call, for 3b633bae4e31807a67ef8ca32f7d4273247adcde ?

**Comment by laurynas-biveinis** [comment]
Vlad, did you test perfschema.no_threads? I have added your snipped to the 5.7.11 merge in progress and get

--- /Users/laurynas/percona/mysql-server/mysql-test/suite/perfschema/r/no_threads.result    2016-03-01 15:08:55.000000000 +0300
+++ /Users/laurynas/percona/obj-merge-5.7.11-asan/mysql-test/var/log/no_threads.reject  2016-03-01 15:31:20.000000000 +0300
@@ -45,5 +45,11 @@
 wait/synch/mutex/mysys/THR_LOCK_myisam lock    mi_create.c:
 select \* from performance_schema.session_connect_attrs;
 PROCESSLIST_ID ATTR_NAME   ATTR_VALUE  ORDINAL_POSITION
+3  _os osx10.11    0
+3  _client_name    libmysql    1
+3  _pid    99593   2
+3  _client_version 5.7.11-4    3
+3  _platform   x86_64  4
+3  program_name    mysqltest   5
 update performance_schema.setup_instruments set enabled='YES';
 drop table test.t1;

Looking at the other testcases in perfschema that query this table I see that they never record its exact contents.

**Comment by vlad-lesin** [comment]
New testing: http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1083/

> threadpool_common.cc:threadpool_remove_connection: should dec_connection_count call be moved after the remove_global_thread call, for 3b633ba ?

Yes, also condition "extra_connections_count > 0" is added in  close_connections() for waiting for all connections to be closed loop.

> Vlad, did you test perfschema.no_threads? I have added your snipped to the 5.7.11 merge in progress and get

Yes, I have tested, but the query returned empty result. Anyway, the result of the query does not matter, the fact of the query execution without crash does matter. That's why I just added "--disable-result-log" command in the test code.

**Comment by laurynas-biveinis** [comment]
LGTM

**Pull request merged**
