### PR TITLE
Fixed lp:1680510 (rpl_diff.inc in 5.7 does not compare data from different servers) (5.7)

### PR DESCRIPTION
**Pull request by percona-ysorokin**
Because of the changes in 5.7 'include/rpl_diff.inc' introduced by
commit mysql/mysql-server@61e2172 this MTR function used to connect to the
same server when querying data for comparison. As the result, it used to
always succeed regardless of data being different or not.

Fixed by adding '--defaults-group-suffix=' back to '--exec $MYSQL'.

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/804/

**Review by laurynas-biveinis — APPROVED** [review]

**Review by robgolebiowski — APPROVED** [review]
LGTM

**Comment by laurynas-biveinis** [comment]
This one should go upstream and to the seed PS 8.0 branch as well

**Comment by percona-ysorokin** [comment]
@laurynas-biveinis, Submitted patches to upstream.
Is there an initial PS 8.0 branch somewhere?

**Comment by laurynas-biveinis** [comment]
@percona-ysorokin, https://github.com/laurynas-biveinis/percona-server/tree/mysql-8.0.0-percona-patches. I'm in process of making a 8.0.1 one if you OK with waiting one or two days.

**Comment by percona-ysorokin** [comment]
No problem. This can definitely wait.

**Pull request merged**
