### PR TITLE
Tokudb mtr default 5.7

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
http://jenkins.percona.com/job/mysql-5.7-param/191/

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
LGTM

**Comment by george-lorch** [comment]
Looks good, two questions:
Will the engines/iuds and engines/funcs tests be run against TokuDB now with it as the default engine?
Have you or do you plan to change the jenkins templates now to remove the separate TokuDB loops?

**Comment by laurynas-biveinis** [comment]
The plan is as follows:

The separate TokuDB treatment will be 95% removed from Jenkins. Param jobs will not run engines/\* with TokuDB as the default engine anymore, and param job users will have the ability to run that by specifying the corresponding params.

The trunk job will run engines/\* with TokuDB as the default engine, and that's the only TokuDB-specific treatment that will be in Jenkins.

**Comment by george-lorch** [comment]
Ack, that makes some sense [--suite=engines/funcs --mysqld=--default-storage-engine=tokudb] etc...

**Pull request merged**
