### PR TITLE
PS-5427 Document the correct distribution upgrade process for Percona…

### PR DESCRIPTION
**Pull request by patrickbirch**
… Server

Added the process to upgrade the distribution in-place with Percona Server already installed - 5.7

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
(changed the base branch from 8.0 to 5.7)

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
If 5.6 PR followed GCA, this one does not: there is only one commit, so there is no merge from 5.6

**Comment by patrickbirch** [comment]
i will fix. thanks

**Comment by patrickbirch** [comment]
I have merged with 5.6 and updated the 5.7 upgrading doc. It still comes out as one commit for two files. Is that correct, or should I commit them separately? Thanks.

**Comment by laurynas-biveinis** [comment]
This is not a GCA process, please check the Confluence

**Comment by patrickbirch** [comment]
Thanks. I will double-check and see what I missed.

**Review by dutow — APPROVED** [review]
For GCA pull requests, please wait until all versions are reviewed , and merge them together.

Will there be an 8.0 version? If yes, that needs a PR too. If no, it needs a null merge PR.

**Pull request merged**
