### PR TITLE
PS-4759: Percona Server Crashing when the stored procedure called the second time in the same session

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PS-4759

Bug was fixed already in commit https://github.com/percona/percona-server/commit/f3019ec2978ce9c00fedfbbe6d51120290be28da, just added testcase for it.

GCA merge from https://github.com/percona/percona-server/pull/4733

### CODE REVIEW

**Review by kamil-holubicki — COMMENTED** [review]
As per GCA process, is it am-PS-4759 merged into am-PS-4759-8.0? I'm not sure.

**Comment by voodam** [comment]
> As per GCA process, is it am-PS-4759 merged into am-PS-4759-8.0? I'm not sure.

Yes, it was bad merge, fixed. I decided for some reason that should be one commit, not two. Now should be ok.

**Comment by kamil-holubicki** [comment]
https://ps80.cd.percona.com/view/Parallel%20MTR/job/percona-server-8.0-pipeline-parallel-mtr/289/

**Review by kamil-holubicki — APPROVED** [review]
LGTM

**Pull request merged**
