### PR TITLE
PS-5931: Allow temporary tables without PKs with sql_require_primary_key

### PR DESCRIPTION
**Pull request by dutow**
The original implementation disables craeting temporary tables with
primary keys. However, the reasoning behind the variable (row based/mixed
replication) is invalid for them, as temporary tables are never
replicated in this mode.

This change alows temporary tables without primary keys even when
sql_require_primary_key is ON.

### CODE REVIEW

**Review by satya-bodapati — COMMENTED** [review]
any mtr tests that cover this change?

**Comment by dutow** [comment]
Specifcally, no - I can extend one. But without this change, check-testcase fails now that I reverted that change in it.

**Comment by satya-bodapati** [comment]
> Specifcally, no - I can extend one. But without this change, check-testcase fails now that I reverted that change in it.

Good to have one explicitly because checktestcase is mtr behaviour and can be disabled with option

**Comment by dutow** [comment]
I've updated the create test.

**Review by satya-bodapati — APPROVED** [review]

**Pull request merged**
