### PR TITLE
Merge upstream 5.7.22 into Percona Server

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link (--big-test)
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1807/

`rocksdb.add_index_inplace_sstfilewriter`
`tokudb.type_timestamp`
`tokudb.type_timestamp_explicit`
Already re-recorded.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Upstream extracted a few tests out of main suite and create a new not-tested-by-default suite audit_null. To keep the testing, we have to add audit_null to the default suite list, and check if there are any our tests that can be moved (grep for have_null_audit_plugin.inc in the main suite)

**Comment by laurynas-biveinis** [comment]
The above change is sufficient to test by a ```--suite=audit_null``` run (and a local ./mtr run to inspect the default suite list in the header which then can be cancelled)

**Comment by percona-ysorokin** [comment]
`main.bug60782` and `main.bug86209` MTR test cases moved to the `audit_null`
suite following changes introduced by the fix for upstream Bug #27008133
"MY_MESSAGE CAUSES SERVER CRASH WHEN HANDLING MYSQL_AUDIT_GENERAL_RESULT EVENT"
(commit mysql/mysql-server@745c07b6495)
(commit mysql/mysql-server@0eaacc5418c).
`audit_null` added to the list of default test suites in
`mysql-test/mysql-test-run.pl`.

**Comment by percona-ysorokin** [comment]
Jenkins build link (--suite=audit_null)
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1811/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
