### PR TITLE
Merge upstream 5.7.12 into Percona Server

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/187

**Comment by laurynas-biveinis** [comment]
main.mysql_upgrade shows a testsuite result diff error everywhere

**Comment by percona-ysorokin** [comment]
The branch sent for review already has the fix for "main.mysql_upgrade".

**Comment by laurynas-biveinis** [comment]
CRLF line endings in the newly added testcases? Too late to fix now (I assume the same went to 5.5 and 5.6 merges), just something to note in the future

**Comment by laurynas-biveinis** [comment]
LGTM

**Pull request merged**
