### PR TITLE
Merge 5.5.48

### PR DESCRIPTION
**Pull request by vlad-lesin**
Merge 'mysql-5.5.48'

The fix for

commit 2735f0b92020c8ac4bd07d7ea843a0946b19e8ad
Author: Venkatesh Duggirala venkatesh.duggirala@oracle.com
Date:   Tue Dec 1 15:38:11 2015 +0530

```
Bug#21205695        DROP TABLE MAY CAUSE SLAVES TO BREAK
```

is changed as Percona's code already contains "append_identifier()" function
which can convert charsets. The fix is in setting thread charset for String
instances on generating "DROP" statement for binary log in
mysql_rm_table_no_locks().

Added testcases for 73556, 74670, 76277.

http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1205/

As for "explain_filename" unit test I can't repeat the fail both for PS and MySQL in Centos7-64.

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Is the explain_filename failure pre-existing one?

**Comment by laurynas-biveinis** [comment]
This merge also takes the upstream fix for https://bugs.launchpad.net/percona-server/5.5/+bug/1521120, please mention it in the commit message (git commit --amend, no Jenkins re-run is needed).

Once the explain_filename is clarified, this is OK to push. Please update the bug above and https://blueprints.launchpad.net/percona-server/+spec/merge-5.5.48 when you do

**Comment by vlad-lesin** [comment]
> Is the explain_filename failure pre-existing one?

5.5 trunk contains the failure too http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-trunk/574/BUILD_TYPE=debug,Host=ubuntu-wily-32bit/consoleText

> This merge also takes the upstream fix for https://bugs.launchpad.net/percona-server/5.5/+bug/1521120, please mention it in the commit message (git commit --amend, no Jenkins re-run is needed).

Is mentioned.

**Comment by laurynas-biveinis** [comment]
LGTM

**Pull request merged**
