### PR TITLE
Fix lp:1702903 (Cannot build Percona Server on Debian Stretch) (5.6)

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build links:
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1946 (OpenSSL)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1947 (YaSSL)

**Review by laurynas-biveinis — COMMENTED** [review]
LGTM provided that EC- cipher testsuite changes are merged correctly to 5.6? The reason being that 5.6+ already supported EC ciphers with OpenSSL 1.0 as a result of fixing https://bugs.mysql.com/bug.php?id=82935 / https://bugs.launchpad.net/percona-server/+bug/1622034

**Review by george-lorch — APPROVED** [review]
You might want to re-roll/matrix reload the bad jenkins tests just to be sure.

**Comment by percona-ysorokin** [comment]
EC- cipher testsuite changes were indeed not necessary. They were added just for symmetry reasons. Reverted.

**Comment by percona-ysorokin** [comment]
Updated Jenkins build links:
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1952/ (OpenSSL)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1953/ (YaSSL)

**Comment by percona-ysorokin** [comment]
@laurynas-biveinis @georgelorch  As there were no code changes (only EC-ciphers fixes and comment corrections in the MTR test cases) since the last review and Jenkins builds are much more stable now, I am going to merge this PR.

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
