### PR TITLE
PS-8854: Convert audit_log_filter plugin to a component

### PR DESCRIPTION
**Pull request by oleksandr-kachan**
https://jira.percona.com/browse/PS-8854

The most significant changes implemented during audit_log_filter
plugin conversion to a component:
- System and status variables rewritten to work with
  component_status_var_service and component_sys_var_service API.
- The read_buffer_size sysvar is global now. The reason for this change
  is that component_sys_var_service doesn't support session variables.
- Removed filter_id system variable. Added audit_log_session_filter_id()
  UDF instead. The reason for the change is again lack of support for
  session variables in component_sys_var_service.
- Added support for audit events of mysql_event_tracking_parse type.
- Data sent along with audit events was changed in 8.1 for most of the
  audit events. Component was adjusted to handle changed events format.

### CODE REVIEW

**Comment by oleksandr-kachan** [comment]
https://ps80.cd.percona.com/view/8.0%20parallel%20MTR/job/percona-server-8.0-param-parallel-mtr/22/

**Comment by percona-ysorokin** [comment]
`component_audit_log_filter.status_var_log_size` fails when run with `--repeat=2`
`./mysql-test/mtr component_audit_log_filter.status_var_log_size --repeat=2`
```
[ 33%] component_audit_log_filter.status_var_log_size  [ pass ]   1299
[ 66%] component_audit_log_filter.status_var_log_size  [ fail ]
        Test ended at 2023-10-20 14:10:18

CURRENT_TEST: component_audit_log_filter.status_var_log_size
--- /home/yura/ws/percona-server-8.1/mysql-test/suite/component_audit_log_filter/r/status_var_log_size.result	2023-10-20 16:08:19.833045454 +0300
+++ /home/yura/ws/percona-build-8.0_zenfs-release_gcc12/mysql-test/var/log/status_var_log_size.reject	2023-10-20 17:10:18.204438653 +0300
@@ -9,6 +9,7 @@
 OK
 Audit_log_filter_current_size Ok
 Audit_log_filter_total_size Ok
+Audit_log_filter_current_size and Audit_log_filter_total_size should be equal
 SELECT audit_log_filter_set_user('%', 'log_all');
 audit_log_filter_set_user('%', 'log_all')
 OK
```

**Comment by percona-ysorokin** [comment]
Also under ASan from gcc-12
`./mysql-test/mtr --debug-server --sanitize component_audit_log_filter.filtering_udf_audit_admin_priv`
```
Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f50960ef498 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x7f506fb57468 in audit_log_filter::SysVars::set_session_filter_id(THD*, unsigned long) /home/yura/ws/percona-server-8.1/components/audit_log_filter/sys_vars.cc:915
    #2 0x7f506fa764ed in audit_log_filter::AuditLogFilter::notify_event(audit_log_filter::audit_event_class_t, void const*) /home/yura/ws/percona-server-8.1/components/audit_log_filter/audit_log_filter.cc:489
    #3 0x7f506fa76b05 in notify /home/yura/ws/percona-server-8.1/components/audit_log_filter/audit_log_filter.cc:133
    #4 0x562a6d3e1741 in THD::event_notify(st_mysql_event_generic*) /home/yura/ws/percona-server-8.1/sql/sql_class.cc:3803
    #5 0x562a6d98ec93 in event_tracking_dispatch /home/yura/ws/percona-server-8.1/sql/sql_audit.cc:340
    #6 0x562a6d98f8b3 in event_tracking_dispatch_error /home/yura/ws/percona-server-8.1/sql/sql_audit.cc:355
    #7 0x562a6d992282 in mysql_event_tracking_query_notify(THD*, unsigned long, char const*) /home/yura/ws/percona-server-8.1/sql/sql_audit.cc:1112
    #8 0x562a6d559ca6 in mysql_execute_command(THD*, bool) /home/yura/ws/percona-server-8.1/sql/sql_parse.cc:5249
    #9 0x562a6d55c1e8 in dispatch_sql_command(THD*, Parser_state*, bool) /home/yura/ws/percona-server-8.1/sql/sql_parse.cc:5714
    #10 0x562a6d55ef8e in dispatch_command(THD*, COM_DATA const*, enum_server_command) /home/yura/ws/percona-server-8.1/sql/sql_parse.cc:2205
    #11 0x562a6d562a55 in do_command(THD*) /home/yura/ws/percona-server-8.1/sql/sql_parse.cc:1521
    #12 0x562a6d967920 in handle_connection /home/yura/ws/percona-server-8.1/sql/conn_handler/connection_handler_per_thread.cc:309
    #13 0x562a706df524 in pfs_spawn_thread /home/yura/ws/percona-server-8.1/storage/perfschema/pfs.cc:3044
    #14 0x7f50932d2ac2 in start_thread nptl/pthread_create.c:442
```
This happens for many other tests as well.

**Comment by percona-ysorokin** [comment]
Under ASan from gcc-12
```
[ 40%] component_audit_log_filter.filtering_udf_audit_admin_priv w6  [ fail ]
        Test ended at 2023-10-20 13:55:40

CURRENT_TEST: component_audit_log_filter.filtering_udf_audit_admin_priv
mysqltest: At line 4: Query 'UNINSTALL COMPONENT 'file://component_audit_log_filter'' failed.
ERROR 3540 (HY000): Unregistration of service implementation 'event_tracking_command.component_audit_log_filter' provided by component 'component_audit_log_filter' failed during unloading of the component.
In included file /home/yura/ws/percona-server-8.1/mysql-test/suite/component_audit_log_filter/inc/audit_comp_uninstall.inc: 4
included from /home/yura/ws/percona-server-8.1/mysql-test/suite/component_audit_log_filter/t/filtering_udf_audit_admin_priv.test: 30
```
Sporadic, does not happen when the test is run individually, only when the whole suite is run.

**Comment by oleksandr-kachan** [comment]
> component_audit_log_filter.status_var_log_size fails when run with --repeat=2

Fixed

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
