### PR TITLE
[BLD-1213] Add Ubuntu 18.10 for PS-80

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
@EvgeniyPatlan why I have to review this?

**Comment by EvgeniyPatlan** [comment]
@laurynas-biveinis I've added you due to license changes

**Comment by laurynas-biveinis** [comment]
@EvgeniyPatlan I have no idea about any licence changes, please ask Tyler

**Comment by EvgeniyPatlan** [comment]
@laurynas-biveinis Ihave found that we have  used old license GPL instead of GPLv2 so I just updated license string in rpm according to upstream

**Review by delgod — APPROVED** [review]

**Pull request merged**
