### PR TITLE
PS-4473: core-file directive is setting 'Max core file size' to

### PR DESCRIPTION
**Pull request by robgolebiowski**
unlimited on Ubuntu 17.10

Moved core-file to early variables so it would be initlialized before
my_init_signals which depends on it.

### CODE REVIEW

**Comment by robgolebiowski** [comment]
https://jenkins.percona.com/job/mysql-5.7-param/1865/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
It looks like other flags of test_flags accessed in my_init_signals - TEST_SIGINT and TEST_NO_STACKTRACE - require moving --gdb and --skip-stacktrace to early options too?

**Comment by robgolebiowski** [comment]
JR => https://jenkins.percona.com/job/mysql-5.7-param/1873/

**Review by laurynas-biveinis — APPROVED** [review]

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
