### PR TITLE
5.7 ps bug1631309

### PR DESCRIPTION
**Pull request by ihanick**
#1219 
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/534/

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
See 5.6 PR

**Comment by ihanick** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/676/
- rebase to fresh 5.7
- merge changes from 5.6
- in opposite to 5.6 buf_flush_LRU_list already returns sum of evicted and flushed 
(buf_flush_do_batch *n_processed = res.first + res.second, std::pair filled in buf_flush_batch https://github.com/percona/percona-server/blob/0217ba5091c94eef00002433bf5ca1029d5ff588/storage/innobase/buf/buf0flu.cc#L1898 )
Thus, just 1ms increment for sleep time and do not try to flush more than number of pages in LRU changes ported from 5.6-ps-bug1631309.

**Review by laurynas-biveinis — APPROVED** [review]
LGTM, but please wait for an OK before pushing

**Comment by ihanick** [comment]
Large buffer pool tests done with https://github.com/laurynas-biveinis/percona-server/tree/bug1631309-test
lru_fix

Can I merge both 5.6 ( #1219 ) and 5.7?

**Comment by laurynas-biveinis** [comment]
Yes, please!

**Pull request merged**
