### PR TITLE
PS-3841 (5.7): Fix QRT compilation warning when linked statically

### PR DESCRIPTION
**Pull request by inikep**
…d of the query_response_time plugin

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Are lower versions affected?
Please edit the bug title to something like "QRT compilation warning when linked statically"
Are other plugins shipped by us affected?

**Comment by inikep** [comment]
1. Other plugins like semisync, version_token, connection_control, tokudb_backup don't have `#ifndef MYSQL_SERVER` but are not affected as they are allowed only for dynamic compilation with `MODULE_ONLY`
2. 5.5 and 5.6 are not affected because of `COMPILE_DEFINITONS` typo in `plugin.cmake` what causes that `-DMYSQL_SERVER` is not added to command line

**Comment by laurynas-biveinis** [comment]
I mean, other our not upstream plugins such as audit_log?

**Comment by inikep** [comment]
I checked all plugins and only QRT seems to be affected.

**Comment by laurynas-biveinis** [comment]
@inikep, is this ready for review?

**Comment by inikep** [comment]
It is not ready. It will be finished after PS-3871

**Comment by inikep** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1686/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
