### PR TITLE
Merge upstream 5.6.37 into Percona Server (ASAN post fix)

### PR DESCRIPTION
**Pull request by percona-ysorokin**
Fixed problem with compiling 'segfault-t.cc' gunit test under ASAN.

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Self approving

**Comment by laurynas-biveinis** [comment]
Upstream?

**Comment by percona-ysorokin** [comment]
@laurynas-biveinis This is not upstream

From the commit message
***
Reverted 'EXPECT_DEATH_IF_SUPPORTED' part ('unittest/gunit/segfault-t.cc') of the
Oracle fix for the Bug #85671
"segfault-t failing under recent AddressSanitizer"
(https://bugs.mysql.com/bug.php?id=85671)
(commit mysql/mysql-server@bb3f159) in favor of Percona fix for lp:1676847
"segfault-t failing under recent AddressSanitizer"
(https://bugs.launchpad.net/percona-server/+bug/1676847)
(commit e0f0741)

This is the part where Oracle in order to fix the problem with different ASAN message decided to just remove the test case, whereas our fix was in extending alternative error message ".*ASAN:(DEADLYSIGNAL|SIGSEGV).*". I left our changes and just missed re-arrangement of the `pint` variable in the initial merge commit.

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1976/

**Pull request merged**
