### PR TITLE
MYR-23 : warning: variable length array is used [-Wvla]

### PR DESCRIPTION
**Pull request by george-lorch**
- Changed use of vla to my_malloc/my_free

### CODE REVIEW

**Comment by george-lorch** [comment]
No jenkins as the code change is entirely within the MyRocks SE.

**Review by laurynas-biveinis — APPROVED** [review]
LGTM, but AFAIK upstream cares about warnings - do you have any guess why they haven't seen this one then?

**Comment by george-lorch** [comment]
I do not know why they have not seen/fixed it but I suspect it is either some gcc version difference or some inherited flags difference. This one I am planning to send upstream, just ran out of time today to do it.

**Comment by george-lorch** [comment]
Actually, this should probably use std::unique_ptr instead of raw C type. I'll fix and push.

**Comment by laurynas-biveinis** [comment]
std::vector then, unique_ptr is suboptimal with arrays

**Comment by laurynas-biveinis** [comment]
Ignore my last comment if you are keeping my_*

**Comment by george-lorch** [comment]
Yeah, I already pushed a change that uses my_ and unique_ptr then later saw your comment on vector. I think for this particular use case, where resizing is not needed, and it is desirable to keep my_*, and only scoped lifetime management of allocated blob is needed, that the unique_ptr is probably the way to go.

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by george-lorch** [comment]
Sigh, upstream chose a different and IMHO more strained approach for something that is minimal impact https://github.com/facebook/mysql-5.6/pull/458/files...I think ours is simpler and less intrusive for some effectively no impact in results.

**Comment by george-lorch** [comment]
Closing as we will inherit a fix in the next upstream refresh.

**Pull request closed without merging**
