### PR TITLE
Prepare tokudb for mysql 8

### PR DESCRIPTION
**Pull request by prohaska7**
How to bootstrap tokudb on Mysql 8?  This pull request is 1 of 4 needed to run tokudb on Mysql 8, and it compiles and runs on Percona server 5.7.  A follow on branch compiles a stripped down tokudb on Mysql 8 and runs some tests.  See https://github.com/prohaska7/tokudb-tools/tree/master/mysql-8.0 for details.  Most of the interesting tokudb features still need patches to the Mysql code.

Mysql 8 changed the compiler options and now includes -Wunused-parameter.  Tokudb has lots of functions with unused parameters so tokudb does not compile with this compiler option.  We could remove this compiler option from the CFLAGS used to compile tokudb, or we could investigate all of the warnings.  Rather than just removing this compiler option, this pull request annotates the unused parameters. In addition, many internal functions have been simplified by removing unused parameters.

This pull request implements the set of open tables as a std c++ unordered map since Mysql 8 renamed the API to its hash table and I did not want to deal with this ugly API change.  The choice of data structure is a compile time option.

Copyright (c) 2018, Rik Prohaska
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

### CODE REVIEW

**Comment by george-lorch** [comment]
This is fantastic, thanks Rich. It has many things that I have already made some patches for but not yet merged to 5.6/5.7.
In order to keep things sane, I will reconcile what I have done with your work and see if it makes sense to append my changes to yours.
For the purposes of keeping 5.6 and 5.7 branches as consistent as possible, I am going to cherry pick as much of this work as I can back to 5.6, then merge it forward to 5.7 via our GC merge process. That means that this particular pull request will eventually get closed without merging, but, your work (and credit) will still go into TokuDB 5.6 and 5.7 (and 8.0).

The server side patches for 8.0 are still being figured out, particularly on how to deal with the new data dictionary. RFR may get re-worked a little to be more of a server side implementation of some of the state tracking so that it and MyRocks can share some common logic where it makes sense.

**Comment by prohaska7** [comment]
Hello George,
Looking forward to the merge of your code and my code.  Let me know if you are interested in the other 3 branches.  2 branches in PerconaFT (pre-8 and tokudb-803) to get the FT code to compile in mysql 8, and 1 more branch in percona-server (tokudb-804) to implement the new handler API.  These additional branches get a basic tokudb to compile and run on mysql 8.

Many features missing including clustering keys and compression row format.  Either need a mysql patch or a new patchless implementation (if possible).  What is the plan?

Features including PFS, RFR, are turned off.  Partitions are not implemented.

**Comment by george-lorch** [comment]
Hey @prohaska7 just FYI, I can not use this PR as-is, but, I can use most of the changes. I am going to re-work the commit history, squashing related items but keeping them separated into a 'commit-per-fix'. I am also going to apply all of this to 5.6 and merge forward to 57 (and eventually 8.0) to keep the diffs minimal across branches and remove some of the #ifdef-ing to just use new structures across all branches. You will retain full credit and copyright for the work. I will add commentary here with links to new pull requests for the changes and close this PR once all of the changes have been successfully taken in, tested, reviewed, and merged into our branches. Thanks again for starting us on this.

**Comment by prohaska7** [comment]
Hello @georgelorchpercona, Glad to see that this work will help bootstrap tokudb on mysql 8.

**Pull request closed without merging**
