### PR TITLE
Bug1525407 5.6

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
http://jenkins.percona.com/job/percona-server-5.6-param/1233/

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Co-assigning this and https://github.com/percona/percona-server/pull/668 to @georgelorchpercona for DB-998

**Comment by george-lorch** [comment]
LGTM

**Comment by percona-ysorokin** [comment]
LGTM, only minor comments from 5.5

**Comment by laurynas-biveinis** [comment]
http://jenkins.percona.com/job/percona-server-5.6-param/1240/

**Comment by percona-ysorokin** [comment]
LGTM

**Pull request merged**
