### PR TITLE
Mistake fixed

### PR DESCRIPTION
**Pull request by MichaelMonashev**

### CODE REVIEW

**Review by alina-derkach-oaza — APPROVED** [review]
Good. Thank you.

**Comment by patrickbirch** [comment]
Thank you. We will merge this pull request when the next version of Percona Server is released.

**Comment by patrickbirch** [comment]
This pull request is being closed because documentation has been moved to another repository.

**Comment by MichaelMonashev** [comment]
@patrickbirch , did you fix mistake in new repository?

**Comment by patrickbirch** [comment]
Yes. The mistake is in a pull request in the documentation repository and will be fixed when PS 8.0 is released. 
Thank you.

**Comment by MichaelMonashev** [comment]
@patrickbirch , I did not find it here https://github.com/percona/pxc-docs/pulls?q=is%3Apr .

**Comment by patrickbirch** [comment]
https://github.com/percona/psmysql-docs/pull/26

**Pull request closed without merging**
