### PR TITLE
Merge mysql 5.7.44 part 1

### PR DESCRIPTION
**Pull request by VarunNagaraju**
https://jira.percona.com/browse/PS-8977

- Raised MYSQL_VERSION_PATCH to 44 in MYSQL_VERSION file.
- Raised PERCONA_INNODB_VERSION to 48 in univ.i file.
- Fixed the innodb.deadlock_detect testcase.
- Fixed innodb.deadlock_detect, tokudb.type_date and tokudb.type_temporal_fractional testcases.
- Fixed hanging keyring_vault tests under ASAN.
- Removed constness of some struct members to support compilation with gcc-13 and clang-17.
- Disabled stack overrun check and ODR violation checks for ASAN runs along disabling some tests from running in an ASAN environment.
-  Suppresses the memory leak warnings in ASAN environment caused by the latest version of python.

### CODE REVIEW

**Comment by VarunNagaraju** [comment]
https://ps57.cd.percona.com/job/percona-server-5.7-param/601/

**Comment by percona-ysorokin** [comment]
@VarunNagaraju 
`tokudb.type_date` and `tokudb.type_temporal_fractional` MTR test cases are failing.
Most probably because of the
```
The [STR_TO_DATE()](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_str-to-date) function did not perform complete range checking on the string to be converted, so that it was possible to pass to it a string which would yield an invalid date, such as '2021-11-31'. (Bug #108782, Bug #34704094)
```

**Comment by percona-ysorokin** [comment]
@VarunNagaraju Also, please port this `keyring_vault` ASan fix from 8.0 to this branch
https://github.com/percona/percona-server/pull/5137/commits/965a12a0add39eb70ab4ee7481ad467e635a967e

**Comment by percona-ysorokin** [comment]
@VarunNagaraju I created a patch for gcc-13 / clang-xxx combination
https://github.com/percona-ysorokin/percona-server/commits/merge-mysql-5.7.44-part-1-gcc13_clang17
Please, import it to your branch.

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
