### PR TITLE
Merge Bugfix lp:719368 from 5.6 to 5.7

### PR DESCRIPTION
**Pull request by ihanick**

### CODE REVIEW

**Comment by ihanick** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/466/

**Review by laurynas-biveinis — APPROVED** [review]
Needs a Jenkins run, otherwise looks good

**Comment by ihanick** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/471/

**Comment by ihanick** [comment]
finished ci tests run:
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/473/

**Pull request merged**
