### PR TITLE
Ps 5.7 myr 15

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/497

**Review by laurynas-biveinis — APPROVED** [review]
See 5.6

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
See 5.6

**Comment by george-lorch** [comment]
New merge from 5.6 and jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/511/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
