### PR TITLE
Merge upstream 5.5.59 into Percona Server

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
https://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1628/
https://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1627/ (--big-test)

`main.information_schema-big` and `main.variables-big` were broken even before 5.5.57 - need to be fixed separately.
`innodb.innodb_bug14676111` is very unstable - absolutely blue in 1628 but fails on a half of the nodes in 1627 (the same behavior is observed in 5.5.57)

**Review by laurynas-biveinis — APPROVED** [review]
It seems they also fixed https://bugs.mysql.com/bug.php?id=71330 without noticing

**Comment by laurynas-biveinis** [comment]
@percona-ysorokin, have you filed a JEN issue for Perl packages for rpl.rpl_manual_change_index_file ?

**Comment by percona-ysorokin** [comment]
@laurynas-biveinis 
Reported https://jira.percona.com/browse/JEN-758

**Pull request merged**
