### PR TITLE
Add filtering by `sql_command` (5.7)

### PR DESCRIPTION
**Pull request by gl-sergei**

### CODE REVIEW

**Comment by gl-sergei** [comment]
I will rebase on the trunk once PR #736 gets in

**Comment by gl-sergei** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/311/

**Comment by gl-sergei** [comment]
The branch is updated and based on latest 5.7 trunk. Jenkins finally (almost) completed: http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/314/

**Comment by laurynas-biveinis** [comment]
LGTM

**Pull request merged**
