### PR TITLE
fix for DOC-751 (mentioning Ubuntu 18.04) and DOC-752 (percona-releas…

### PR DESCRIPTION
**Pull request by fiowro**
…e 0.1.6), 5.6 version

### CODE REVIEW

**Comment by hrvojem** [comment]
5.5?

**Comment by fiowro** [comment]
https://www.google.com/search?q=site%3Apercona.com%2Fdoc+installing+"17.10" (the search query proposed on jira to locate relevant docs) shows no sign of PS 5.5...

**Comment by hrvojem** [comment]
Yes, but we still support/release 5.5 packages for Bionic (also repository packages changes have affect on 5.5 as well).

**Comment by fiowro** [comment]
Ok. Created pull request starting from 5.5 :)

**Pull request closed without merging**
