### PR TITLE
Ps 5.7 db 1012

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/446/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.6

**Comment by george-lorch** [comment]
Changed code and mtr test to use DBUG_EXECUTE_IF. New jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/451/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same changes as in 5.6

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/454/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as in 5.6

**Comment by george-lorch** [comment]
Changes pushed and new jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/458/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comments as for 5.6

**Comment by george-lorch** [comment]
Ditto, made/merged change and new jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/460/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
