### PR TITLE
Bug #1464468 fix. Slave crash with malformed binlog event

### PR DESCRIPTION
**Pull request by vlad-lesin**
See

https://bugs.launchpad.net/percona-server/+bug/1464468/comments/1
https://bugs.launchpad.net/percona-server/+bug/1464468/comments/2

for details.

The fix is in clearing the number of binlog table maps in
binlog_cache_data::flush_pending_event() even if the number
of pending events is zero.

There is the following call stack.

write_locked_table_maps()-(as thd->binlog_table_maps is 0)->binlog_start_trans_and_stmt()->THD::binlog_write_table_map->register_binlog_handler()

If thd->binlog_table_maps is not zero then binlog handlerton is not registered
and the following ha_savepoint() call will not initialize memory where
savepoint binlog position is stored what leads to storing uninitialized value
in binlog_cache_data::cache_log.pos_in_file on ha_rollback_to_savepoint()
execution and damaging binary log file.

http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/884/

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
The fix probably is a good fix, but I'm unable to say that I
understand the implications of unconditional binlog table map clearing
even after spending considerable time for looking into this.

If I understand the issue correctly, a way to rephrase it would be
that ha_savepoint does not call the binlog handler in the conditions
here. If that's correct, then the simplest fix which is also IMHO
easier to reason about would be simply registering the binlog handler
in ha_savepoint if needed before the actual work. It seems to work on
this testcase and variations thereof (i.e. no exception handler and
ROLLBACK in trigger itself).

I.e.

```
diff --git a/sql/handler.cc b/sql/handler.cc
index 2c41180..6b72904 100644
--- a/sql/handler.cc
+++ b/sql/handler.cc
@@ -2220,9 +2220,13 @@ int ha_savepoint(THD *thd, SAVEPOINT *sv)
   int error=0;
   THD_TRANS *trans= (thd->in_sub_stmt ? &thd->transaction.stmt :
                                         &thd->transaction.all);
-  Ha_trx_info *ha_info= trans->ha_list;
   DBUG_ENTER("ha_savepoint");

+  if (mysql_bin_log.is_open()) // add a clarifying comment here
+    register_binlog_handler(thd, thd->in_multi_stmt_transaction_mode());
+
+  Ha_trx_info *ha_info= trans->ha_list;
+
   for (; ha_info; ha_info= ha_info->next())
   {
     int err;
```

What do you think? If you are confident in your fix then we can
probably go ahead with it too after some further review.

Testcase comments:
- Let's merge it with the bug 1438990 testcase if possible, as it's
  another case of the same upstream bug.
- Please add --source include/show_binlog_events.inc on the master
  side to see what's actually going on with the binlog (consequently
  let's limit the testcase to RBR only).
- Please add checks that slave actually syncs with master. This is
  interesting as for upstream this testcase is another crash on the
  slave side in unpack_row.

If that's not too much effort, please update bug 76727 contribution
with the sum of the current and the previous fix or at least let them
know what else must be handled.

**Comment by vlad-lesin** [comment]
> The fix probably is a good fix, but I'm unable to say that I
> understand the implications of unconditional binlog table map clearing
> even after spending considerable time for looking into this.

https://bugs.launchpad.net/percona-server/+bug/1464468/comments/2 explains this.

I think your fix is good too. I have created new branch with your fix: https://github.com/vlad-lesin/percona-server/tree/5.6-bug-1464468-mailformed-binlog-event-2 .

> Let's merge it with the bug 1438990 testcase if possible, as it's
> another case of the same upstream bug.

I do not agree, this is not the same bug. The first bug is about binary log table maps for savepoint. This bug is about corrupted savepoint position.

> Please add --source include/show_binlog_events.inc on the master
> side to see what's actually going on with the binlog (consequently
> let's limit the testcase to RBR only).

I am not sure this is necessary because the assertion takes place before flush to binary log.

> Please add checks that slave actually syncs with master. This is
> interesting as for upstream this testcase is another crash on the
> slave side in unpack_row.

This bug is not the same as 1438990.

**Comment by laurynas-biveinis** [comment]
Vlad - 

the second comment on the bug explains why this fix works on the testcase, but what I had in mind is that I could not figure out whether clearing table maps unconditionally is safe outside this bug as well.

Re. whether it's the same bug or not, please consider the following: before any fix is applied, the original 1438990/76727 testcase crashes the slave in unpack_row, and the testcase for the current bug crashes with the same stacktrace. If the fix for 1438990 is applied, the 1438990 testcase passes, and the current bug testcase crashes master debug build or breaks replication for release build. I'd conclude that 1464468 fix is what makes 1438990 fix complete and should be considered its part.

If you think that your fix is safe in general, outside what's discussed in comment 2, go ahead with the original fix. Re. the testcases, again, up to you. Re. showing binlog events, no of course that is not required to verify the fix, it just helps with understanding how this case should work.

**Comment by vlad-lesin** [comment]
> the second comment on the bug explains why this fix works on the testcase, but what I had in mind is that I could not figure out whether clearing table maps unconditionally is safe outside this bug as well.

I understand your doubts and have them too. But I also have doubts about the second fix ( see the first comment here https://github.com/percona/percona-server/pull/116 ). I just put hopes on regression tests. But the second fix is more obvious so I would prefer more obvious code.

> Re. whether it's the same bug or not, please consider the following: before any fix is applied, the original 1438990/76727 testcase crashes the slave in unpack_row, and the testcase for the current bug crashes with the same stacktrace. If the fix for 1438990 is applied, the 1438990 testcase passes, and the current bug testcase crashes master debug build or breaks replication for release build. I'd conclude that 1464468 fix is what makes 1438990 fix complete and should be considered its part.

I don't agree because these bugs have different nature. If we think as above and we have any bug fix which allows to make some progress in code execution and this progress is the cause of another bug on some conditions then we should join such bug fixes, i.e. 1438990 fix allows to use savepoints in triggers for replication, then we should consider any other replication savepoint bugs as a big fix of 1438990. I don't think this logic is correct.

> showing binlog events, no of course that is not required to verify the fix, it just helps with understanding how this case should work.

Ok, agree. Except that it would be useful to remove the "debug-only" limitation for the test case. Will do.

**Pull request closed without merging**
