### PR TITLE
Lwt bug lp1657737 simpl 5.7 gca

### PR DESCRIPTION
**Pull request by vlad-lesin**
See https://github.com/percona/percona-server/pull/1970.

http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1283/

### CODE REVIEW

**Review by percona-ysorokin — CHANGES_REQUESTED** [review]
The same test case comments as in 5.6

**Comment by vlad-lesin** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1285/

**Review by percona-ysorokin — APPROVED** [review]
LGTM with the same minor comment as in 5.6

**Review by laurynas-biveinis — COMMENTED** [review]
Same as for 5.6

**Pull request merged**
