### PR TITLE
PS-3901 (5.6): Fix -DWITHOUT_xxx_STORAGE_ENGINE=ON for some plugins

### PR DESCRIPTION
**Pull request by inikep**

### CODE REVIEW

**Comment by inikep** [comment]
https://jenkins.percona.com/job/percona-server-5.6-param/2127/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for #2250

**Comment by inikep** [comment]
The commit message is updated.

**Review by laurynas-biveinis — COMMENTED** [review]
The diff LGTM, but it looks like it's not a merge from 5.5?

**Comment by inikep** [comment]
This in not GCA as `storage/innobase/CMakeLists.txt` was recently modified: 
https://github.com/percona/percona-server/pull/2212/files

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
