### PR TITLE
PS-4759: Percona Server Crashing when the stored procedure called the second time in the same session

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PS-4759

Bug was fixed already in commit f3019ec2978ce9c00fedfbbe6d51120290be28da, just added testcase for it.

### CODE REVIEW

**Review by kamil-holubicki — CHANGES_REQUESTED** [review]
1. When I revoke the mentioned fix, MTR test still passes. Test is not complete/something else fixed the issue?
2. We should use GCA

**Comment by voodam** [comment]
> 1. When I revoke the mentioned fix, MTR test still passes. Test is not complete/something else fixed the issue?

Fixed. For some reason first variant of test worked as expected for Percona Server 5.7.21, but not for current 5.7 branch.

> 2. We should use GCA

Done, branch rewinded to GCA.

**Review by kamil-holubicki — COMMENTED** [review]
Looks fine.
1. Would it be possible to rename it to ```parser_local_transaction```?
2. Please squash commits and write a proper commit message with details.
3. Please create PR with merge to 8.0

**Comment by voodam** [comment]
> 1. Would it be possible to rename it to `parser_local_transaction`?

Ok, but trasformations, not transaction.

> 2. Please squash commits and write a proper commit message with details.

Please give some clues what is missed in message. I can try to understand better how parser works here, but now for me it's just de-facto working testcase, without deep understanding.

**Comment by kamil-holubicki** [comment]
I've started Jenkins
https://ps57.cd.percona.com/job/percona-server-5.7-pipeline/29116/
This PR looks fine.
Please create another PR with merge to 8.0 (am-PS-4759 -> am-PS-4759-8.0 -> 8.0) to follow GCA process.

**Comment by voodam** [comment]
> Please create another PR with merge to 8.0 (am-PS-4759 -> am-PS-4759-8.0 -> 8.0) to follow GCA process.

Done: https://github.com/percona/percona-server/pull/4896

**Comment by kamil-holubicki** [comment]
https://ps57.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/29448/

**Review by kamil-holubicki — APPROVED** [review]
LGTM

**Pull request merged**
