### PR TITLE
Ps 5.7 tdb 114

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1699/

**Comment by george-lorch** [comment]
Re-pushed a re-commit in order to properly credit Rik Prohaska, code is same, only commit id, author, and message has been changed.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.6

**Comment by george-lorch** [comment]
OK, fixed up, found a little more vestigial code that could be removed as a result of the removal of the HASH, jenkins here : https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1716/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
