### PR TITLE
Ps 5.7 lp1626206

### PR DESCRIPTION
**Pull request by george-lorch**

### CODE REVIEW

**Comment by george-lorch** [comment]
Supersedes https://github.com/percona/percona-server/pull/65
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/438/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comment as for 5.6

**Comment by george-lorch** [comment]
Remerged from 5.6 fixup changes

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/443/

**Comment by george-lorch** [comment]
Same somment as 5.6, readded Toku specific test and new jenkins cycle http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/445/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
