### PR TITLE
Fix lp:1659992 "Function over userstat tables cause mysql to crash" (5.6)

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/job/percona-server-5.6-param/1786/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.5

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link (as no code changes since the previous commit, just single test run)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1791/

**Review by laurynas-biveinis — APPROVED** [review]

**Review by robgolebiowski — APPROVED** [review]
LGTM

**Pull request merged**
