### PR TITLE
Revert "MYR-27 : facebook/webscale mysqldump changes"

### PR DESCRIPTION
**Pull request by george-lorch**
This reverts commit 131a6a47afe540d3b48d7f00a84e946c5fe1f77d.

Conflicts:
	client/client_priv.h
	client/mysqldump.c

### CODE REVIEW

**Comment by george-lorch** [comment]
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1998/

**Comment by laurynas-biveinis** [comment]
Why does this need to be reverted?

**Comment by laurynas-biveinis** [comment]
Ah, it's 5.6, I see then. But please still state the reason for any future reference

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by george-lorch** [comment]
Ahh, yeah, sorry, I just used 'git revert' which generated the commit message and autocommitted and didn't even think to go back and change the message. I'll amend and push that before merging. Following that I'll have a NULL merge to 5.7 that I won't bother with a review.

**Pull request merged**
