### PR TITLE
Merge upstream 5.7.13 into Percona Server

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/215

**Comment by laurynas-biveinis** [comment]
There appear to be test regressions in scalability_metrics, and unit test pfs_instr-oom

Do you have a baseline upstream run?

**Comment by percona-ysorokin** [comment]
pfs_instr-oom - is a regression in the upstream 5.7.13. It can be easily reproduced on any platform (here is a Jenkins link to the MySQL Server 5.7.13 test run - http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/208).
The bug is already reported to Oracle - Bug #81868 "pfs_instr-oom unit test fails on MySQL Server 5.7.13"
(http://bugs.mysql.com/bug.php?id=81868)

scalability_metrics failures are connected to our favorite lp:1441139 "handle_fatal_signal (sig=11) in Queue<PROF_MEASUREMENT>::pop | sql/sql_profile.h:127 | handle_fatal_signal (sig=11) in my_lfind" (https://bugs.launchpad.net/percona-server/+bug/1441139)

It looks like WL#5705 "Audit log plugin fine-grained pre-filtering" (commit 1edc52a) just helped to reveal the problem faster. I believe because of additional MYSQL_AUDIT_CONNECTION_DISCONNECT event generated.

**Comment by laurynas-biveinis** [comment]
Can you disable pfs_instr-oom then if it's not something we can fix trivially?
Can you confirm that scalability_metrics issue is indeed really 1441139, and if yes, disable it too?

**Comment by percona-ysorokin** [comment]
Valgrind helped to reveal problem in pfs_instr-oom. It is fixed now.
scalability_metrics is disabled via 'disabled.def'.

**Comment by percona-ysorokin** [comment]
Updated Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/216

**Comment by laurynas-biveinis** [comment]
What is the pfs_instr-oom fix?

**Comment by percona-ysorokin** [comment]
`git diff mysql-5.7.13 storage/perfschema/unittest/pfs_instr-oom-t.cc`
diff --git a/storage/perfschema/unittest/pfs_instr-oom-t.cc b/storage/perfschema/unittest/pfs_instr-oom-t.cc
index db74c9c..5259f14 100644
--- a/storage/perfschema/unittest/pfs_instr-oom-t.cc
+++ b/storage/perfschema/unittest/pfs_instr-oom-t.cc
@@ -243,11 +243,15 @@ void test_oom()
   file_1= find_or_create_file(&fake_thread, &dummy_file_class, "dummy", 5, true);
   ok(file_1 != NULL, "create file");
   release_file(file_1);
+  cleanup_file_hash();
   cleanup_instruments();

   stub_alloc_always_fails= true;
+  fake_thread.m_filename_hash_pins = NULL;
+  init_file_hash(&param);
   file_2= find_or_create_file(&fake_thread, &dummy_file_class, "dummy", 5, true);
   ok(file_2 == NULL, "oom (create file)");
+  cleanup_file_hash();

   /\* Create socket. */
   stub_alloc_always_fails = false;
@@ -422,7 +426,7 @@ void do_all_tests()

 int main(int, char **)
 {
-  plan(28);
+  plan(33);
   MY_INIT("pfs_instr-oom-t");
   do_all_tests();
   return 0;

**Comment by laurynas-biveinis** [comment]
LGTM, and please send the pfs_instr-oom fix by OCA to the upstream bug.

**Pull request merged**
