### PR TITLE
ps-4689 Document TokuHotBackup use for replication

### PR DESCRIPTION
**Pull request by patrickbirch**
Added a hotbackup section to the backup doc
Rewrote section

### CODE REVIEW

**Comment by george-lorch** [comment]
submodule commit pointers have been updated, these should not be here.

**Review by george-lorch — CHANGES_REQUESTED** [review]
Please undo the submodule commit pointer changes.

**Comment by patrickbirch** [comment]
Will do.

**Comment by patrickbirch** [comment]
Removed submodules from the commit

**Comment by george-lorch** [comment]
OK, so this is merging from patrickbirch:ps-5.6-4689 into percona-server:8.0?  Shouldn't we be starting this work in 5.6, then merging forward into 8.0?

**Comment by patrickbirch** [comment]
OK. I'll redo this for the 5.6 version. No version is selected in the Jira ticket.

**Comment by patrickbirch** [comment]
Will redo PR with 5.6 version

**Pull request closed without merging**
