### PR TITLE
PS-8951 [8.0]: Merge percona-202302 to percona-202305 tags from fb-mysql-8.0.28

### PR DESCRIPTION
**Pull request by inikep**
1. Update rocksdb submodule to [8.5.1](https://github.com/facebook/rocksdb/commit/3885d7652)

2. Add new MyRocks variables `rocksdb_block_cache_numshardbits`, `rocksdb_check_iterate_bounds`, `rocksdb_compact_lzero_now`, `rocksdb_file_checksums`, `rocksdb_max_file_opening_threads`, and `rocksdb_partial_index_ignore_killed`.

3. Add clone plugin variables `clone_compression_algorithm` and `clone_zstd_compression_level`.

4. Change default values of MyRocks variables: `rocksdb_compaction_sequential_deletes`, `rocksdb_compaction_sequential_deletes_count_sd`, `rocksdb_compaction_sequential_deletes_window`, `rocksdb_force_flush_memtable_now`

5. Cherry-pick the following commits from `percona-202305`:
- [9708eb799ef Fix MTR test: rocksdb_cf_per_partition](https://github.com/facebook/mysql-5.6/commit/9708eb799ef)
- [14df9f16d1f Implement RocksDB file-level checksums (#1280)](https://github.com/facebook/mysql-5.6/commit/14df9f16d1f)
- [2ece56eaba4 update rocksdb to 8.1.fb](https://github.com/facebook/mysql-5.6/commit/2ece56eaba4)
- [4c5fa165bd7 Index read fixes (#1292)](https://github.com/facebook/mysql-5.6/commit/4c5fa165bd7)
- [35a178add15 Add intermediate rocksdb_sources build step](https://github.com/facebook/mysql-5.6/commit/35a178add15)
- [4475c80fb7e Fix clang 15 -Wunused-but-set-variable warnings in MyRocks (#1304)](https://github.com/facebook/mysql-5.6/commit/4475c80fb7e)
- [b08cc536f14 Update rocksdb to 8.2.fb](https://github.com/facebook/mysql-5.6/commit/b08cc536f14)
- [c3f1703231d make rocksdb build compatible with make 4.3 in centos 9](https://github.com/facebook/mysql-5.6/commit/c3f1703231d)
- [3ba4f39d4ef Fix issues 1200 and 1295, add rocksdb_compact_lzero_now global variable (#1309)](https://github.com/facebook/mysql-5.6/commit/3ba4f39d4ef)
- [e8dc455741e Fix handling of consecutive sentinel values](https://github.com/facebook/mysql-5.6/commit/e8dc455741e)
- [18381192a55 Add different compression choice](https://github.com/facebook/mysql-5.6/commit/18381192a55)
- [63b8aae2051 Cleanup non-null pointer args, increase const correctness (#1311)](https://github.com/facebook/mysql-5.6/commit/63b8aae2051)
- [e7877a4c8ef Update rocksdb to 8.3.fb](https://github.com/facebook/mysql-5.6/commit/e7877a4c8ef)
- [38b673f1966 Move default PATH setting from CMake to get_rocksdb_files.sh (#1312)](https://github.com/facebook/mysql-5.6/commit/38b673f1966)
- [e4751cae643 Set rocksdb_large_prefix to ON and deprecate this system variable (#1322)](https://github.com/facebook/mysql-5.6/commit/e4751cae643)
- [12c1f02ee7a MyRocks: implement attachable transaction support (#1314)](https://github.com/facebook/mysql-5.6/commit/12c1f02ee7a)
- [f902321c89f Set JemallocAllocatorOptions::num_arenas=8](https://github.com/facebook/mysql-5.6/commit/f902321c89f)
- [6bd68a82d49 Skipping transaction API cause delete row fail to find key](https://github.com/facebook/mysql-5.6/commit/6bd68a82d49)
- [0bfdb056c66 check upper and lower bound for writebatchwithindex](https://github.com/facebook/mysql-5.6/commit/0bfdb056c66)
- [730887a4080 Add rocksdb_block_cache_numshardbits for issue 1336 (#1339)](https://github.com/facebook/mysql-5.6/commit/730887a4080)
- [7316be1a000 Remove extra assert in Rdb_writebatch_impl class (#1337)](https://github.com/facebook/mysql-5.6/commit/7316be1a000)
- [51116fb65fc Changing default rocksdb_compaction_sequential_deletes values](https://github.com/facebook/mysql-5.6/commit/51116fb65fc)
- [9f03dbf7fca Update RocksDB submodule to 8.5.fb](https://github.com/facebook/mysql-5.6/commit/9f03dbf7fca)
- [14eaf68501b Always assume existence of persisted autoincrement values for MyRocks (#1329)](https://github.com/facebook/mysql-5.6/commit/14eaf68501b)
- [0d685cb30ab Adding rocksdb_max_file_opening_threads sysvar](https://github.com/facebook/mysql-5.6/commit/0d685cb30ab)
- [b4ab6e57547 Clear cached memory on PinnableSlice](https://github.com/facebook/mysql-5.6/commit/b4ab6e57547)
- [f7397f3264b Check sentinel in more places](https://github.com/facebook/mysql-5.6/commit/f7397f3264b)
- [7d17329e6b6 Add option to ignore killed flag for materialization](https://github.com/facebook/mysql-5.6/commit/7d17329e6b6)
- [b3aa1d995f3 Update RocksDB submodule to 8.5.1.fb](https://github.com/facebook/mysql-5.6/commit/b3aa1d995f3)
- [98da68c1020 Fix for snapshot conflict on SK due to concurrent update](https://github.com/facebook/mysql-5.6/commit/98da68c1020)
- [6c3a1007975 Fix rocksdb.partial_index_debug](https://github.com/facebook/mysql-5.6/commit/6c3a1007975)
- [c7e72aac10d Cleanup pointers in method signatures called from (#1355)](https://github.com/facebook/mysql-5.6/commit/c7e72aac10d)
- [bb43e885b4c Follow up fixes to SK update concurrency test cases](https://github.com/facebook/mysql-5.6/commit/bb43e885b4c)
- [1993a1ecd8f Run clang-format on storage/rocksdb (#1359)](https://github.com/facebook/mysql-5.6/commit/1993a1ecd8f)

6. Skipped MyRocks commits:
- [1a0f5813eb6 Add dict_register_dd_table_id api support for rocksdb dd (#1298)](https://github.com/facebook/mysql-5.6/commit/1a0f5813eb6)
- [78b9bbdd07e Add set/get server version api (#1296)](https://github.com/facebook/mysql-5.6/commit/78b9bbdd07e)
- [5813c1a07e7 Add ddst_dict_init api support for rocksdb ddse (#1297)](https://github.com/facebook/mysql-5.6/commit/5813c1a07e7)
- [3afb4bdcb87 Add rocksdb_is_supported_system_table api support for rocksdb dd (#1299)](https://github.com/facebook/mysql-5.6/commit/3afb4bdcb87)
- [b0ba3d0eabc Load rocksdb se plugin if default dd se is rocksdb (#1285)](https://github.com/facebook/mysql-5.6/commit/b0ba3d0eabc)
- [35465cd9ef6 Adding sys var to enable RBR BI inconsistency checks on TTL tables](https://github.com/facebook/mysql-5.6/commit/35465cd9ef6)
- [3e0f5470243 Add multiple checks for clone (#1294)](https://github.com/facebook/mysql-5.6/commit/3e0f5470243)
- [ff311772923 Clean up test output files for rocksdb.bypass_select_unsupported](https://github.com/facebook/mysql-5.6/commit/ff311772923)
- [b354aaea77e Disable DESC for mysql.password_history (#1287)](https://github.com/facebook/mysql-5.6/commit/b354aaea77e)
- [0b72cc83885 MyRocks clone: add missing donor mutex unlocks on error exits (#1317)](https://github.com/facebook/mysql-5.6/commit/0b72cc83885)
- [6a41c742257 Refactor the acquisition of DDSE handlerton (#1319)](https://github.com/facebook/mysql-5.6/commit/6a41c742257)
- [bb3054fffff Fix a too-strict assertion for --help if default_dd_storage_engine=RocksDB (#1326)](https://github.com/facebook/mysql-5.6/commit/bb3054fffff)
- [de72f7b19be Add SQL-level support for storing the DD schema in MyRocks (#1325)](https://github.com/facebook/mysql-5.6/commit/de72f7b19be)
- [ab522f6df7c Handle log archiver archiving past the clone SE sync point (#1328)](https://github.com/facebook/mysql-5.6/commit/ab522f6df7c)
- [4466a082ea0 implement handler API table_exists_in_engine for myrocks (#1321)](https://github.com/facebook/mysql-5.6/commit/4466a082ea0)
- [6893ef0ee00 support get hlc query](https://github.com/facebook/mysql-5.6/commit/6893ef0ee00)
- [48f004aeac5 Moving BI inconsistency check to just before commit](https://github.com/facebook/mysql-5.6/commit/48f004aeac5)
- [0e85153f199 Fix EXPLAIN output MRR reference for DESC](https://github.com/facebook/mysql-5.6/commit/0e85153f199)
- [02fea595be5 Adding more logging to easier investigation](https://github.com/facebook/mysql-5.6/commit/02fea595be5)
- [492829044e6 dont bulk load for table metadata change](https://github.com/facebook/mysql-5.6/commit/492829044e6)
- [0eb86345355 Reimplement InnoDB data dictionary INFORMATION_SCHEMA views through server layer (#1342)](https://github.com/facebook/mysql-5.6/commit/0eb86345355)
- [106ec6eb3dd update rocksdb suite MTR for rocksdb DD (#1338)](https://github.com/facebook/mysql-5.6/commit/106ec6eb3dd)
- [71c8fbc41ca Fix/skip some tests in MTR main suite for MyRocks DDSE (#1358)](https://github.com/facebook/mysql-5.6/commit/71c8fbc41ca)

7. Skipped upstream commits:
- [723b602b921 Fix MTR test: innodb_gis.geometry](https://github.com/facebook/mysql-5.6/commit/723b602b921)
- [7a705e3cb9a Fix flaky test: main.dd_bootstrap_debug](https://github.com/facebook/mysql-5.6/commit/7a705e3cb9a)
- [fb76715e3df allow disable rocksdb plugins when it isn't ddse engine](https://github.com/facebook/mysql-5.6/commit/fb76715e3df)
- [c779b885bea Backporting Bug#33733529 : CLI options deprecation warnings of mysqldump are printed to stdout.](https://github.com/facebook/mysql-5.6/commit/c779b885bea)
- [f13c53853cb Fix perfschema to stop returning unallocated records](https://github.com/facebook/mysql-5.6/commit/f13c53853cb)
- [67467e6a29c Add support for DSCP (Differentiated Services Field) to MySQL Clone Plugin for remote clone process (#1277)](https://github.com/facebook/mysql-5.6/commit/67467e6a29c)
- [e0e61f6773f Update main.mysqld--help-notwin test for rocksdb file checksum](https://github.com/facebook/mysql-5.6/commit/e0e61f6773f)
- [dce73870ac0 Check for valid binlog_smallest_max_gtid before printing it](https://github.com/facebook/mysql-5.6/commit/dce73870ac0)
- [37b8624c43e Backport Bug#33733529 : CLI options deprecation warnings of mysqldump are printed to stdout.](https://github.com/facebook/mysql-5.6/commit/37b8624c43e)
- [27fd7f3eb9e Fix clone plugin build on macOS (#1289)](https://github.com/facebook/mysql-5.6/commit/27fd7f3eb9e)
- [5c992301654 Fix rpl.rpl_semi_sync_alias flakiness](https://github.com/facebook/mysql-5.6/commit/5c992301654)
- [d9de1d4b0fc Add held lock tracking](https://github.com/facebook/mysql-5.6/commit/d9de1d4b0fc)
- [ca29d617ba9 Backport Bug#34693784 TABLE ACCESS SERVICE INDEX READ MAP ISSUES](https://github.com/facebook/mysql-5.6/commit/ca29d617ba9)
- [918a960057c Increase max rwlock classes for pfs_example tests](https://github.com/facebook/mysql-5.6/commit/918a960057c)
- [d6ea428a722 Fixing AB/BA deadlock between Sys_var_gtid_purged_for_tailing and binlog_change_to_apply](https://github.com/facebook/mysql-5.6/commit/d6ea428a722)
- [edc9eb56084 Reset select_limit when iterating through indexes](https://github.com/facebook/mysql-5.6/commit/edc9eb56084)
- [751a0ace0c7 Reduce failures of rpl.rpl_heartbeat_timestamp](https://github.com/facebook/mysql-5.6/commit/751a0ace0c7)
- [9f20243ce88 Introduce boot-lldb and manual-boot-lldb options](https://github.com/facebook/mysql-5.6/commit/9f20243ce88)
- [d1ca8b276d6 Do not keep restarting shardbeater loop but restrict to 5 attempts](https://github.com/facebook/mysql-5.6/commit/d1ca8b276d6)
- [2af02f6e27e Replace LOCK_thd_remove with MDL based mutex](https://github.com/facebook/mysql-5.6/commit/2af02f6e27e)
- [8a94981ffba Rerecord main.mysqld--help-notwin](https://github.com/facebook/mysql-5.6/commit/8a94981ffba)
- [5fdafcc1379 Fixing rpl_raft_wait_for_ack](https://github.com/facebook/mysql-5.6/commit/5fdafcc1379)
- [6835925114e Bug#33300271: EXPLAIN + CTE + temporary table leads to crash mysqld](https://github.com/facebook/mysql-5.6/commit/6835925114e)
- [e8044640853 Filter out glog messages from errorlog for log_buffered-big test](https://github.com/facebook/mysql-5.6/commit/e8044640853)
- [d630c52b336 Convert LOCK_thd_security_ctx to MDL mutex](https://github.com/facebook/mysql-5.6/commit/d630c52b336)
- [5c2852e1451 Bug #34638573 Compile MySQL with clang 15 (#1293)](https://github.com/facebook/mysql-5.6/commit/5c2852e1451)
- [4b39a6d91d3 Semisync histogram double free (#1290)](https://github.com/facebook/mysql-5.6/commit/4b39a6d91d3)
- [904ebee09f9 Reduce flakiness of rpl.rpl_gtid-innodb_sys_header](https://github.com/facebook/mysql-5.6/commit/904ebee09f9)
- [230acbc64c1 Stabilize max_db_connections tests](https://github.com/facebook/mysql-5.6/commit/230acbc64c1)
- [12328068e5b Remove an unused variable exposed by clang 15 -Wunused-but-set-variable (#1303)](https://github.com/facebook/mysql-5.6/commit/12328068e5b)
- [d1d23e7c7ca Make blackhole engine transactional](https://github.com/facebook/mysql-5.6/commit/d1d23e7c7ca)
- [bb793bfdc6b Add Write_throttle_lag STATUS VAR](https://github.com/facebook/mysql-5.6/commit/bb793bfdc6b)
- [44ffdebd1bf Bug#33457946: main.index_merge_innodb fails sporadically on pb2 daily trunk](https://github.com/facebook/mysql-5.6/commit/44ffdebd1bf)
- [ac0055427b2 Test exception handling of privacy plugin](https://github.com/facebook/mysql-5.6/commit/ac0055427b2)
- [78c19548229 Bug #34638573 Compile MySQL with clang 15 (#1302)](https://github.com/facebook/mysql-5.6/commit/78c19548229)
- [3984cc1728c Convert write throttle lag metric to be a peak](https://github.com/facebook/mysql-5.6/commit/3984cc1728c)
- [5e89a2ddf6f Fix mtr test rpl_raft_dump_raft_logs: Wait at least one heartbeat after restarting an instance before attempting to promote to it](https://github.com/facebook/mysql-5.6/commit/5e89a2ddf6f)
- [d60403ae110 Update nesting test results](https://github.com/facebook/mysql-5.6/commit/d60403ae110)
- [41d4cc7b17b Fix acl_lookup_table memory leak](https://github.com/facebook/mysql-5.6/commit/41d4cc7b17b)
- [b0e803dcbdf add option --data-path for mysqldump](https://github.com/facebook/mysql-5.6/commit/b0e803dcbdf)
- [fa6b6659249 Fix flakiness in rpl per_channel tests](https://github.com/facebook/mysql-5.6/commit/fa6b6659249)
- [f421600ca13 Fix the remaining -Wunqualified-std-cast-call warnings (#1305)](https://github.com/facebook/mysql-5.6/commit/f421600ca13)
- [e1491ff4493 Bug#34776172 MacOS: silence deprecated use warnings from XCode >= 14 (#1306)](https://github.com/facebook/mysql-5.6/commit/e1491ff4493)
- [8cc47c6b81b Adding mtr test for data endorsement policy](https://github.com/facebook/mysql-5.6/commit/8cc47c6b81b)
- [8ba919930c1 Fix flakiness for rpl.rpl_innodb_auto_increment](https://github.com/facebook/mysql-5.6/commit/8ba919930c1)
- [6f53260d166 Add a new error code for plugin disabled feature](https://github.com/facebook/mysql-5.6/commit/6f53260d166)
- [d70edeb07bd Rerecord mtr tests for privacy suite](https://github.com/facebook/mysql-5.6/commit/d70edeb07bd)
- [48fd2d7d172 Convert mutex LOCK_plugin_install into MDL_mutex](https://github.com/facebook/mysql-5.6/commit/48fd2d7d172)
- [acb0b195852 Add --no-defaults to MYSQLADMIN calls](https://github.com/facebook/mysql-5.6/commit/acb0b195852)
- [2f11e1fabae Updating Data Endorsement Test with new checks and Result](https://github.com/facebook/mysql-5.6/commit/2f11e1fabae)
- [074bf59af77 Refactor data dictionary transaction isolation setting (#1316)](https://github.com/facebook/mysql-5.6/commit/074bf59af77)
- [9f101f0fe19 fix QUERY_LOG_GAP_LOCK ER_CANT_OPEN_FILE log crashes the server](https://github.com/facebook/mysql-5.6/commit/9f101f0fe19)
- [06be6b96e34 Explicitly specify char signedness for the underlying enum type (#1313)](https://github.com/facebook/mysql-5.6/commit/06be6b96e34)
- [6a1cd206632 Re-enable AC timeout tests](https://github.com/facebook/mysql-5.6/commit/6a1cd206632)
- [4aee2d60212 Making RaftReplicationParam part of every hook call](https://github.com/facebook/mysql-5.6/commit/4aee2d60212)
- [6164cf02748 Remove transaction position from THD if we're rolling back](https://github.com/facebook/mysql-5.6/commit/6164cf02748)
- [0a81c404586 Expose THD::kill_query_with_error via thd API](https://github.com/facebook/mysql-5.6/commit/0a81c404586)
- [eb68bc959f6 Copy admission_control_wait_events_errors test to thread_pool suite](https://github.com/facebook/mysql-5.6/commit/eb68bc959f6)
- [ef5b9b10155 Put back the kill test](https://github.com/facebook/mysql-5.6/commit/ef5b9b10155)
- [002cf1f9a00 Fix tests for all vars](https://github.com/facebook/mysql-5.6/commit/002cf1f9a00)
- [201aea9e3d0 Fix allow_binlog_writes_on_raft_follower for primary](https://github.com/facebook/mysql-5.6/commit/201aea9e3d0)
- [250a78f5041 Don't run thread_pool/admission_control_wait_events_errors test without thread pool](https://github.com/facebook/mysql-5.6/commit/250a78f5041)
- [80fd0f7349c Use correct hostname pointer in mysqld](https://github.com/facebook/mysql-5.6/commit/80fd0f7349c)
- [02a50c19acf Enable engine specific DD tables (#1334)](https://github.com/facebook/mysql-5.6/commit/02a50c19acf)
- [e2699020978 use record(0) in Raw_record::drop](https://github.com/facebook/mysql-5.6/commit/e2699020978)
- [4f84cf12ae5 Add write_throttle_action_count status var](https://github.com/facebook/mysql-5.6/commit/4f84cf12ae5)
- [0c5d805c16f Adding test to check Privacy PXL for DEP and PP policy](https://github.com/facebook/mysql-5.6/commit/0c5d805c16f)
- [82d13ffb758 Adding two hooks for before and after stopping applier](https://github.com/facebook/mysql-5.6/commit/82d13ffb758)
- [40b9ba00e73 Fixing rpl_raft.rpl_raft_abort_trx_rbr_inconsistency](https://github.com/facebook/mysql-5.6/commit/40b9ba00e73)
- [37b801da4f8 Convert LOCK_plugin_delete and LOCK_global_system_variables to rwlocks](https://github.com/facebook/mysql-5.6/commit/37b801da4f8)
- [b5f75f66133 Expand prefix filtering for show vars and show status](https://github.com/facebook/mysql-5.6/commit/b5f75f66133)
- [cc3dbc1f6ea Fix expand prefix filtering for show vars and show status](https://github.com/facebook/mysql-5.6/commit/cc3dbc1f6ea)
- [f3bafebbb1a Adding ability to send lower bound HLC in resp attrs](https://github.com/facebook/mysql-5.6/commit/f3bafebbb1a)
- [f8f25057470 Fix thread_pool/t/is_columns_is_cs.test regression](https://github.com/facebook/mysql-5.6/commit/f8f25057470)
- [cce75ded065 Added DB_NAME column into performance_schema.sql_finding table](https://github.com/facebook/mysql-5.6/commit/cce75ded065)
- [708b8e59f77 Adding new option to mtr to start debugger only for specific server](https://github.com/facebook/mysql-5.6/commit/708b8e59f77)
- [5599fbacf68 Wait on before_commit on largest opid trx, not last](https://github.com/facebook/mysql-5.6/commit/5599fbacf68)
- [71c5dfddb17 Fixing idempotent recovery cleanup](https://github.com/facebook/mysql-5.6/commit/71c5dfddb17)
- [971a18c8811 print out delta of global usage and global peak in max_tmp_table_size to debug test failures](https://github.com/facebook/mysql-5.6/commit/971a18c8811)
- [5515e562465 Revert "Fix main.myisam_explain_json_non_select_all"](https://github.com/facebook/mysql-5.6/commit/5515e562465)
- [0f854f1be74 Convert host to IP address to avoid loading DNS](https://github.com/facebook/mysql-5.6/commit/0f854f1be74)
- [ea580d2bacf Add a new RPC to return the applied HLC of a database by name](https://github.com/facebook/mysql-5.6/commit/ea580d2bacf)
- [f618aca6967 avoid acquiring LOCK_global_sql_findings when there is no error/warning/note](https://github.com/facebook/mysql-5.6/commit/f618aca6967)
- [10f0fe819b4 Implement sys_var prev_gtid_and_opid](https://github.com/facebook/mysql-5.6/commit/10f0fe819b4)
- [17a3b3f4e40 make "Rows found" comment in mysqldump output support new line in table names](https://github.com/facebook/mysql-5.6/commit/17a3b3f4e40)
- [cf1e6782fc0 add a simple mtr test for thrift server plugin](https://github.com/facebook/mysql-5.6/commit/cf1e6782fc0)
- [6b12b7cfeda Remove fine grain policy check from mtr test](https://github.com/facebook/mysql-5.6/commit/6b12b7cfeda)
- [7c5997d988d add mtr test for basic thrift server select case](https://github.com/facebook/mysql-5.6/commit/7c5997d988d)
- [6fc6b1642a5 Allow bypass rpc to return lower bound HLC](https://github.com/facebook/mysql-5.6/commit/6fc6b1642a5)
- [48d40dea6ad Fix MYSQL_BIN_LOG::update_prev_gtid_and_opid declaration (#1343)](https://github.com/facebook/mysql-5.6/commit/48d40dea6ad)
- [ebe8e1c24f0 Add some comments to AC and scheduler code](https://github.com/facebook/mysql-5.6/commit/ebe8e1c24f0)
- [d942e829aba Fix Raft MTR tests caused by sid_lock during update_prev_opid_and_gtid and applier warning](https://github.com/facebook/mysql-5.6/commit/d942e829aba)
- [b7807a80da9 add have_innodb_ddse.inc file (#1344)](https://github.com/facebook/mysql-5.6/commit/b7807a80da9)
- [32f4d9b97f6 Fix queue score calculation to get fractional results](https://github.com/facebook/mysql-5.6/commit/32f4d9b97f6)
- [49d0964dfc1 Checking for errors when copying binlog cache to raft IO cache](https://github.com/facebook/mysql-5.6/commit/49d0964dfc1)
- [71d4ecc3b74 client/mysqltest.cc: fix Apple clang 14 Release build (#1349)](https://github.com/facebook/mysql-5.6/commit/71d4ecc3b74)
- [1d7a7d8a305 sql/sql_plugin.cc: fix Apple clang 14 Release build (#1351)](https://github.com/facebook/mysql-5.6/commit/1d7a7d8a305)
- [63206ad8a3e Mark main.mysqldump-lra as a Linux-only test (#1347)](https://github.com/facebook/mysql-5.6/commit/63206ad8a3e)
- [50152e9bbdf plugin/test_service_priva … (#1352)](https://github.com/facebook/mysql-5.6/commit/50152e9bbdf)
- [91eff72be4a storage/innobase/dict/dict0dd.cc: fix Apple clang 14 Release build (#1350)](https://github.com/facebook/mysql-5.6/commit/91eff72be4a)
- [2cc41a7afb0 Mark INFORMATION_SCHEMA.SOCKET_DIAG_SLAVES tests as Linux-only (#1348)](https://github.com/facebook/mysql-5.6/commit/2cc41a7afb0)
- [e45cfa65a5a Avoid big allocations in rapidjson](https://github.com/facebook/mysql-5.6/commit/e45cfa65a5a)
- [e781eeb0bc3 add warning support for query exceed parser memory limit](https://github.com/facebook/mysql-5.6/commit/e781eeb0bc3)
- [83065edb1d2 Remove an incorrect assert from (#1356)](https://github.com/facebook/mysql-5.6/commit/83065edb1d2)
- [4a3a1fb55ee Fix group by loose index scan costing](https://github.com/facebook/mysql-5.6/commit/4a3a1fb55ee)
- [36ccf8ec9e9 Release Parser memory after each statement](https://github.com/facebook/mysql-5.6/commit/36ccf8ec9e9)
- [13a93302197 Fix column usage info size accounting for max_column_statistics_size](https://github.com/facebook/mysql-5.6/commit/13a93302197)
- [16fc855ab05 Fix memory leak when opening a table fails](https://github.com/facebook/mysql-5.6/commit/16fc855ab05)

### CODE REVIEW

**Comment by inikep** [comment]
Tested at https://ps80.cd.percona.com/job/percona-server-8.0-param-parallel-mtr/33/

**Comment by percona-ysorokin** [comment]
`rocksdb.file_checksums` fails on ZenFS
```
[  5%] rocksdb.file_checksums 'drop_table_with_delete_range' w6  [ fail ]
        Test ended at 2024-01-10 13:57:32

CURRENT_TEST: rocksdb.file_checksums
mysqltest: At line 28: Command "file_exists" failed with error 1. my_errno=175.
```

**Comment by inikep** [comment]
In the above update:
1. I removed RocksDB Data Dictionary commits (that use `rdb_native_dd.cc` and `rdb_native_dd.h`).
2. I suppressed an error for `rocksdb.file_checksums` (it was too hard to fix).

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
