### PR TITLE
5.7 ps bug1634932

### PR DESCRIPTION
**Pull request by robgolebiowski**

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same as for 5.6

**Comment by robgolebiowski** [comment]
Jenkin's link: http://jenkins.percona.com/job/mysql-5.7-param/614/. There is couple of tests failing due to Jenkin's problems. I have checked them locally and they pass (apart from perfschema.show_sanity:
+5.6    I_S.SESSION_VARIABLES   KILL_IDLE_TRANSACTION), but this was not introduced by this fix.

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Same comments as for 5.6

**Comment by robgolebiowski** [comment]
Jenkins run => http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/636/ (there are some test cases failing, but I have checked them all locally and all are passing).

**Comment by robgolebiowski** [comment]
Jenkins run => http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/640/ There are some tests failing, but I have run them locally and all pass fine.

**Review by laurynas-biveinis — APPROVED** [review]
Since this is an upstream bug, ping me for the next steps after you merge this

**Review by percona-ysorokin — CHANGES_REQUESTED** [review]
The same comments as in 5.6

**Review by percona-ysorokin — APPROVED** [review]

**Pull request merged**
