### PR TITLE
sql_tmp_table: check if table->file is not null before accessing

### PR DESCRIPTION
**Pull request by polachok**
We have experienced a crash on line 813.

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Thank you for the patch, but we need more information in order to process it:
- Do you have a SQL testcase that would hit this this crash?
- Is this Percona Server-specific issue or one shared with MySQL?

**Comment by polachok** [comment]
1) We don't have a testcase to reproduce, it happens randomly on some of our servers with thousands of databases
2) same code can be found in mysql, so it's a shared issue

**Comment by laurynas-biveinis** [comment]
Your server error logs could contain a crashing query recorded at the crash time and that would be helpful for us trying to construct a testcase.

Right now we cannot merge it as-is, because we don't know how why table->file is NULL: we have to analyse why get_new_handler returned NULL in the first place.

**Comment by polachok** [comment]
There's no query in the error.log.
We're currently investigating possibility to enable general.log on problematic servers.
I'll get back to you when I get more information on this problem.

**Pull request closed without merging**
