### PR TITLE
Fix for bug #1432846 (5.6)

### PR DESCRIPTION
**Pull request by gl-sergei**

### CODE REVIEW

**Comment by gl-sergei** [comment]
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/848/

**Comment by gl-sergei** [comment]
updated
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/850/

**Comment by laurynas-biveinis** [comment]
Same minor comments as for 5.5, please merge once it's ready

**Comment by gl-sergei** [comment]
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/852/

**Pull request merged**
