### PR TITLE
PS-3871 (5.6): Typo prevents MYSQL_SERVER to be defined for statically linked plugins

### PR DESCRIPTION
**Pull request by inikep**

### CODE REVIEW

**Comment by inikep** [comment]
https://jenkins.percona.com/job/percona-server-5.6-param/2092/

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by inikep** [comment]
PR was updated to have a minimal set of changes backported from 5.7 required to fix `COMPILE_DEFINITIONS` that is only `storage/innobase/CMakeLists.txt`

**Comment by inikep** [comment]
https://jenkins.percona.com/job/percona-server-5.6-param/2093/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
