### PR TITLE
Fixed lp:1222777. Changed FSF address for new one

### PR DESCRIPTION
**Pull request by gen1us2k**

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
We don't own storage/ndb subtree - please notify Oracle MySQL that the address incorrect there

**Comment by gen1us2k** [comment]
Ok. What to do next? Re-create pull-request without changed files in storage/ndb subtree?

**Comment by laurynas-biveinis** [comment]
Nothing, thank you - I'll create three pull requests for 5.5/5.6/5.7 with your patch and will fix it there

**Comment by laurynas-biveinis** [comment]
https://github.com/percona/percona-server/pull/630, https://github.com/percona/percona-server/pull/631, https://github.com/percona/percona-server/pull/632

**Pull request closed without merging**
