### PR TITLE
[PS-4546] Set unlimited TimeoutSec for ubuntu/debian

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Packaging bugs must be public too - please move to PS and adjust the commit message accordingly

**Comment by EvgeniyPatlan** [comment]
@laurynas-biveinis done. Also I got confirmation from upstream that TimeoutSec should be disabled

**Review by abychko — APPROVED** [review]
looks good to me

**Comment by tplavcic** [comment]
@EvgeniyPatlan How will this work if I specify wrong option in the config file - will it fail immediately or wait unlimited ?

**Comment by EvgeniyPatlan** [comment]
@tplavcic It shouldn't wait timeout and will fail immediately

**Pull request merged**
