### PR TITLE
Squashed commit of the following contribution and added mtr test case:

### PR DESCRIPTION
**Pull request by george-lorch**
commit c75a07867bf84ae5aa56228599b2194d4644a180
Author: Tokiro tokiro.oyama@gmail.com
Date:   Tue May 5 12:25:36 2015 +0200

```
"tokudb_default" evalutates to ROW_TYPE_DEFAULT
```

commit 7446748cbe6b6f2c15b7d49edc198d84a096ba20
Author: Tokiro tokiro.oyama@gmail.com
Date:   Tue May 5 11:47:30 2015 +0200

```
removed ROW_TYPE_TOKU_DEFAULT to the enum row_type
```

commit 102cb5401e2080ad3757fe45d9f8d3ae0a838e6a
Author: Tokiro tokiro.oyama@gmail.com
Date:   Tue May 5 11:46:48 2015 +0200

```
added the recognition of the token "tokudb_default" to the grammar
```

commit 3cf76cb47828e2bd59b3c3c28520cb1226c737dd
Author: Tokiro tokiro.oyama@gmail.com
Date:   Tue May 5 11:31:22 2015 +0200

```
added TOKUDB_DEFAULT token
```

commit 0f55b3a4a05f12e0eca5c1870c44f97434a20134
Author: Tokiro tokiro.oyama@gmail.com
Date:   Tue May 5 11:28:12 2015 +0200

```
added ROW_TYPE_TOKUDB_DEFAULT to enum row_type
```

### CODE REVIEW

**Comment by george-lorch** [comment]
Supersedes #65 
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1410/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
@georgelorchpercona, we have a testcase in the main suite for grammar changes which does not require the SE: tokudb_zip_grammar. A negative InnoDB test should probably be added there too.

**Comment by george-lorch** [comment]
OK, removed the test case and placed appropriate tests in the existing tokudb_zlib_gramar test. Also fixed some issues with the TOKUDB_DEFAULT symbol being associated with ROW_TYPE_DEFAULT instead of creating an appropriate new symbol ROW_TYPE_TOKU_DEFAULT.

**Comment by george-lorch** [comment]
New jenkins http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1415/

**Comment by laurynas-biveinis** [comment]
Looks good, but have you removed the positive TokuDB test? If yes, why? That still tested something that tokudb_zip_grammar couldn't

**Comment by george-lorch** [comment]
OK, re-added the Toku specific test and launched a new jenkins cycle http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1418/

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
