### PR TITLE
PS-5427-Document-the-correct-distribution-upgrade-process-for-Percona…

### PR DESCRIPTION
**Pull request by patrickbirch**
…-Server

Added the process to upgrade a distribution in-place with Percona Server already installed.

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Is this GCA?

**Comment by patrickbirch** [comment]
Yes. I followed the process to make it GCA. Did I miss something?

**Review by laurynas-biveinis — APPROVED** [review]
It's all good, thank you

**Comment by laurynas-biveinis** [comment]
Note that we usually merge branches in full sets, that is, once all 5.6/5.7/8.0 PRs have been approved

**Pull request merged**
