### PR TITLE
row_fomat=tokudb_default is recognized by sql grammar

### PR DESCRIPTION
**Pull request by 26fe**
When a table with the `tokudb_default` format is specified a syntax error is generated. For example:

```
mysql> create table test.t (i int) engine=tokudb row_format=tokudb_default;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tokudb_default' at line 1
mysql> create table test.t (i int) engine=tokudb row_format=tokudb_zlib;
Query OK, 0 rows affected (0.09 sec)

mysql> select version();
+-------------+
| version()   |
+-------------+
| 5.6.23-72.1 |
+-------------+
1 row in set (0.00 sec)
```

The [documentation](http://docs.tokutek.com/tokudb/tokudb-index-using-tokudb.html) states that the `tokudb_default` is an alias for tokudb_zlib format. The patch adds a token `tokudb_default` to the grammar. When the yacc parser recognizes `tokudb_default` it evaluated to `ROW_TYPE_DEFAULT` value.

After the patch:

```
mysql> create table t (i int) engine=tokudb row_format=tokudb_default;
Query OK, 0 rows affected (0.02 sec)

mysql> alter table t row_format=tokudb_uncompressed;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> select table_name, row_format from information_schema.tables where table_schema='test'; 
+------------+---------------------+
| table_name | row_format          |
+------------+---------------------+
| t          | tokudb_uncompressed |
+------------+---------------------+
1 row in set (0.00 sec)

mysql> alter table t row_format=tokudb_default;
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> select table_name, row_format from information_schema.tables where table_schema='test'; 
+------------+-------------+
| table_name | row_format  |
+------------+-------------+
| t          | tokudb_zlib |
+------------+-------------+
1 row in set (0.00 sec)
```

### CODE REVIEW

**Comment by george-lorch** [comment]
Looks good, but curious why 5 individual commits?

**Comment by 26fe** [comment]
I do not remember exactly. It was few month ago. It is a few lines, but I was struggling to find the best way to make the patch acceptable. I am very happy if you accepts it.

**Comment by 26fe** [comment]
(IMHO) Patching the mysql grammar is a short span solution. Adding  a new rowformat requires to patch the grammar. For example if you add a new compression method. 

The best fix is to pass a string to storage engine plugin instead of a tokenized value. The storage engine will become responsible to check if the rowformat is correct.  But it requires a lot of work.

**Comment by george-lorch** [comment]
Agreed, we are looking into ways to expose storage engine specific table/index settings without the need to modify the core server SQL grammar. MariaDB has a nice implementation but it is quite invasive. MySQL 5.7 has some features that use the `CREATE/ALTER TABLE ... COMMENT '...'` with the COMMENT field being like a command argument list. The nice thing about this is that it can easily be parsed, stored and recreated by the storage engine and shows in `SHOW CREATE TABLE/INDEX`. With more and more exposure of fractal tree shape, size, and behavior options this is going to become much needed.

**Comment by george-lorch** [comment]
Superseded by https://github.com/percona/percona-server/pull/1053 and https://github.com/percona/percona-server/pull/1052

Squashed commits and added mtr test case.

**Pull request closed without merging**
