### PR TITLE
Preliminary fix for bug 1679025 / 85835.

### PR DESCRIPTION
**Pull request by percona-ysorokin**

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
This is a quick fix from @laurynas-biveinis 
Although the main problem seems to be much deeper, the fix was confirmed by the customer who requested it.

**Review by george-lorch — APPROVED** [review]
@percona-ysorokin I read through the internal issue history and lightly reviewed the patch. I have never been through this area before so I may be missing many details, but in general, the fix looks harmless. I think though we need to ensure that QA looks very close at this and any impacts it might have to queries that make use of LIMIT to ensure the correct result is returned.

**Review by robgolebiowski — APPROVED** [review]
LGTM

**Comment by percona-ysorokin** [comment]
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/953/

**Comment by laurynas-biveinis** [comment]
I wrote to @peterschwaller why I thought LIMIT handling needs further review

Please prepare upstream / 8.0 seed submission too

**Comment by RoelVdP** [comment]
Discussed with @laurynas-biveinis and agreed that - as far as this ticket and limited patch goes 
 an additional QA run/review is not required.

**Pull request merged**
