### PR TITLE
Fix PS-5270 (xtradb_compressed_columns_consistency_barracuda_compress…

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
…ed_set2 still too big under ASan)

mysqltest keeps in memory all the processed lines, with loops
unrolled. For a testcase with multiple nested loops this results in
big memory usage. Fix by rewriting the testcase logic as server-side
stored procedures, completely eliminating mysqltest memory concerns,
and making the testcase more efficient overall.

https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/36/

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
5.6 PR created for 8.0 branch?

**Comment by laurynas-biveinis** [comment]
Fixed

**Review by percona-ysorokin — APPROVED** [review]
LGTM (apart from wrong base branch for this PR)

Looks really cool. Thanks for doing this.

**Comment by percona-ysorokin** [comment]
Also consider marking this test case with `--source include/big_test.inc`.

**Pull request merged**
