### PR TITLE
PS-1344: Rearrange checks in log_slow_statement() function (5.7)

### PR DESCRIPTION
**Pull request by oleksandr-kachan**
https://jira.percona.com/browse/PS-1344

Rearrange PS specific checks in log_slow_statement() function:
- Check state of thd->enable_slow_log before doing a bunch
  of PS specific checks. This allows to find out if slow log is
  enabled early and avoid unnecessary checks.
- Move collecting of query_exec_time up, do it right after
  thd->enable_slow_log is checked. Getting query_exec_time earlier
  before performing PS speciffic checks will give a more precise
  duration.
- Copy global vars into session ones before doing checks where this
  value is actually used, do it as the next step after query_exec_time
  calculation.

### CODE REVIEW

**Comment by oleksandr-kachan** [comment]
https://ps57.cd.percona.com/job/percona-server-5.7-param/484/

**Review by satya-bodapati — CHANGES_REQUESTED** [review]
Is this pure refactoring? Can you please list the effects of your changes in the commit/github description? I mean "move here to there" type messages do not really convey what you achieved.

**Comment by oleksandr-kachan** [comment]
> Is this pure refactoring? Can you please list the effects of your changes in the commit/github description? I mean "move here to there" type messages do not really convey what you achieved.

Yes, this is just a refactoring. I've extended description a bit, not sure there is anything more to be added there.

**Comment by satya-bodapati** [comment]
> > Is this pure refactoring? Can you please list the effects of your changes in the commit/github description? I mean "move here to there" type messages do not really convey what you achieved.
> 
> Yes, this is just a refactoring. I've extended description a bit, not sure there is anything more to be added there.

Ok, if it is refactoring, then it is fine. It looked like it could result in some improvements.

**Review by satya-bodapati — APPROVED** [review]

**Pull request merged**
