### PR TITLE
[BLD-1012] Add new selinux rules for tokudb and fix flush_caches

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**
Also it include fix for PS-4813

### CODE REVIEW

**Review by abychko — APPROVED** [review]
looks good. OK to merge if QA is OK

**Comment by EvgeniyPatlan** [comment]
@abychko @hrvojem I have updated the review. It works correctly now

**Review by abychko — APPROVED** [review]
OK if tests are OK

**Review by abychko — APPROVED** [review]
ok to merge if test is OK

**Pull request merged**
