### PR TITLE
PS 5.7 clang 6 fixes

### PR DESCRIPTION
**Pull request by dutow**

### CODE REVIEW

**Review by percona-ysorokin — APPROVED** [review]
LGTM with the same comments as in 5.5 and 5.6

**Comment by dutow** [comment]
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1726/

**Comment by laurynas-biveinis** [comment]
@dutow, is https://github.com/percona/percona-server/pull/2236/commits/a9fde2b9d993cab59a764cfa6ae6e83c0517815a upstream?

**Comment by dutow** [comment]
It is

**Comment by laurynas-biveinis** [comment]
Report it (hopefully will fare better than "when "true || false" can be false" one)

**Pull request merged**
