### PR TITLE
Crash when auto incremented column updated in partitioned table

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PS-7856

Use dbug_tmp_use_all_columns/dbug_tmp_restore_column_map as described in 74cc73d as a workaround, because autoincremented column is not used in the query.

This is new PR instead of #4590 to comply GCA process (again).

### CODE REVIEW

**Comment by voodam** [comment]
All commits will be squashed to single after review.

**Comment by voodam** [comment]
I'll wait until https://github.com/percona/percona-server/pull/4589 will be approved, then rebase this PR in the right way and reopen it.

**Review by kamil-holubicki — APPROVED** [review]
lgtm

**Comment by kamil-holubicki** [comment]
@voodam Patch is OK, but it looks like clang formating check fails. Please adjust.
image

**Pull request merged**
