### PR TITLE
Update sequence_table.rst (8.0)

### PR DESCRIPTION
**Pull request by imp3142**
Typo

### CODE REVIEW

**Review by patrickbirch — APPROVED** [review]
LGTM

**Review by alina-derkach-oaza — APPROVED** [review]
LGTM

**Comment by alina-derkach-oaza** [comment]
We will merge this pull request when the next version of Percona Server is released.

**Comment by patrickbirch** [comment]
Closing this pull request. Documentation has been moved to another repository and the issue has been added to a new pull request.

**Pull request closed without merging**
