### PR TITLE
Bug1689489 5.7

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
http://jenkins.percona.com/job/mysql-5.7-param/909/

### CODE REVIEW

**Review by percona-ysorokin — CHANGES_REQUESTED** [review]
The same comments as in 5.6

**Review by robgolebiowski — APPROVED** [review]
LGTM

**Comment by laurynas-biveinis** [comment]
http://jenkins.percona.com/job/mysql-5.7-param/919/

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Pull request merged**
