### PR TITLE
Use POWER8 accelerated crc32

### PR DESCRIPTION
**Pull request by grooverdan**
mysql bug: http://bugs.mysql.com/bug.php?id=74776
mariadb bug: https://mariadb.atlassian.net/browse/MDEV-9288
- Make accelerated checksum available to InnoDB.
- Fall back to slice-by-eight if not available. The mode used is printed on startup.

unittest/gunit/innodb/ut0crc32-t

Before:

1..2
Using software crc32 implementation, CPU is little-endian
ok 1
Using software crc32 implementation, CPU is little-endian
    normal CRC32: real    0.148006 sec
    normal CRC32: user    0.148000 sec
    normal CRC32: sys     0.000000 sec
big endian CRC32: real    0.144293 sec
big endian CRC32: user    0.144000 sec
big endian CRC32: sys     0.000000 sec
ok 2

After:

1..2
Using POWER8 crc32 implementation, CPU is little-endian
ok 1
Using POWER8 crc32 implementation, CPU is little-endian
    normal CRC32: real    0.008097 sec
    normal CRC32: user    0.008000 sec
    normal CRC32: sys     0.000000 sec
big endian CRC32: real    0.147043 sec
big endian CRC32: user    0.144000 sec
big endian CRC32: sys     0.000000 sec
ok 2

Author CRC32 ASM code: Anton Blanchard anton@au.ibm.com.
ref: https://github.com/antonblanchard/crc32-vpmsum

Author: portability - Daniel Black daniel.black@au.ibm.com

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
Hi, thank you for the patch. I tried building it on x86/x86_64 and am getting several CMake errors, with the first one being as follows. You can see full logs at http://jenkins.percona.com/job/mysql-5.7-param/50/
...
CMake Error at cmake/plugin.cmake:125 (ADD_LIBRARY):
  Cannot find source file:

```
ut/crc32_power8/crc32.S
```

...

**Comment by grooverdan** [comment]
@laurynas-biveinis doh. Sorry. forgot to include it in the commit.

FYI I'm also contemplating moving it to msys directory and hooking the binlog checksum implementation to hook to the same place. If so I'll put in a separate PR.

**Comment by laurynas-biveinis** [comment]
@grooverdan, we can merge your current PR right now since it's well-isolated (extra source files, a couple of #ifdef **powerpc**), does not regress on x86_64, so this works well for a Percona Sever unsupported platform. If you move crc32 calculation code to mysys and use it everywhere, this obviously results in a better patch (and I hope Oracle merges it ASAP), but also something that adds to our diff against MySQL, and increases the risk of us breaking it without knowing it.

Thus, do you want us to merge the current patch now or wait for a better patch that has a greater probability of not being merged? (Merging the patch right now and then reviewing a diff from this patch to a better patch is OK too).

**Comment by grooverdan** [comment]
I'm most of the way though a better patch that makes all optimised CRC32 (including SSE) used for binlog and the SQL CRC32 function. Yes, lets hold off on this for now.

**Comment by grooverdan** [comment]
upstream bugs/code to watch:

https://github.com/mysql/mysql-server/pull/41

https://bugs.mysql.com/bug.php?id=79325
https://bugs.mysql.com/bug.php?id=79155
https://bugs.mysql.com/bug.php?id=74776
https://bugs.mysql.com/bug.php?id=79144

http://bugs.mysql.com/bug.php?id=68036 (not sure if this is fixed)

**Comment by dutow** [comment]
Hello!

I'm closing this, as we can't support the POWER8 architecture.

**Pull request closed without merging**
