### PR TITLE
MYR-38 : Percona Server 5.7 jenkins inclusion

### PR DESCRIPTION
**Pull request by george-lorch**
- Altered CMakeLists.txt to check for supported platform and gcc >= 4.8.0. If
  requirements not met, logs reason and exits gently.

### CODE REVIEW

**Comment by george-lorch** [comment]
This is first step in jenkins clean runs. It assures that MyRocks detects unsupported platforms, and gently returns, allowing the build to complete.

Next step is to clean/fix all mtr .cnf and .opt files to properly specify --loose prefix to all overridden variables so server can start and tests can --skip gracefully

**Comment by george-lorch** [comment]
Here is a jenkins run with these changes in place http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/788/

You can see here centos6-32 skipping because of unsupported platform : http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/789/BUILD_TYPE=debug,Host=centos6-32/consoleFull

> 20:57:19 -- Building with MyRocks storage engine
> 20:57:19 -- x86_64 is only platform supported. i686 found. Not building MyRocks

And you can see here, debian-wheezy skipping because of wrong compiler version : http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/788/BUILD_TYPE=debug,Host=debian-wheezy-x64/consoleFull

> 19:29:35 -- Building with MyRocks storage engine
> 19:29:35 -- GCC >= 4.8.0 required. 4.7.2 found. Not building MyRocks

**Review by laurynas-biveinis — COMMENTED** [review]
The changes as they are look good, but please consider
- making the WITH_MYROCKS option tri-state, i.e. ON/OFF/FORCE, where FORCE fails the build on unsupported systems. IMHO this would catch packaging issues etc sooner
- factor out the C++11 check from MyRocks/TokuDB CMakefiles to a common macro

**Comment by george-lorch** [comment]
Good points and along what I was thinking. I believe we should eliminate jenkins specific dancing in Toku and follow this same idea so they both build the same I like the idea of tri-state but that will likely require some coordination between jenkins and RQA team to avoid breaking interim building.

**Comment by george-lorch** [comment]
Thinking a bit more about tri-state. I'm thinking that for engines that should be built/packaged as GA (TokuDB) the default behavior should be FORCE. MTR building can then override that with ON to allow gentle failures on unsupported platforms. But again, this change for TokuDB will require coordination with the 5.7 jenkins template and build/release team to ensure continuity without disrupting builds. That said, I think this tri-state behavior change should be done as a separate task that is maybe done at the same time we enable MyRocks to build in jenkins.

As far as factoring out macros, I'm not quite sure where that would go. In the server code it looks like it should be a new macro file in ./cmake and included into the master ./CMakeLists.txt

**Comment by laurynas-biveinis** [comment]
I'm not sure about FORCE default - PS is supported on 32-bit platforms and the like, and supported should mean works out of the box.

Re. factoring out macros, your locations seem to be correct.

**Comment by george-lorch** [comment]
Re: I guess for people that self build, your point on a default of FORCE is true. Either way, there will need to be platform specific build changes for release builders, i.e. if FORCE is default, non supported platforms will need to override FORCE with OFF in both dev jekins and release jenkins builders; If ON is default, supported platforms will need to override with FORCE in release jenkins builders only. This change will need to be coordinated w/ RQA so they can adjust their release build templates once such a change lands in the trunk. In theory though, with ON as default, release builders should never notice any difference if everything is working correctly, the FORCE would only exist so cmake would fail when things are not exactly correct.

**Comment by george-lorch** [comment]
Jenkins jobs, all just run some common named test from tokudb and rocksdb suites as we don't need total mtr here:
--suite=tokudb,rocksdb,innodb --do-test=gap_lock_error

runs with all default cmake options
-----------------------------------
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/796/

We can see that all platforms pass:
 - None build MyRocks by default
 - centos 6 32 skips TokuDB as an unsupported platform
   - 19:55:50 -- Not building with MyRocks storage engine, you must specify -DWITH_ROCKSDB=1|ON|FORCE to cmake in order to build with MyRocks.
   - 19:55:50 -- Building with TokuDB storage engine = 1
   - 19:55:50 CMake Warning at storage/tokudb/CMakeLists.txt:43 (MESSAGE):
   - 19:55:50   x86_64 is only platform supported.  i686 found.  Not building TokuDB
 - remaining platforms build TokuDB and pass tests
 

-DWITH_TOKUDB=0 -DWITH_ROCKSDB=0
--------------------------------
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/797/
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/800/

There was a jenkins/github issues, so needed a matrix reload.
We can see again all platforms pass:
 - None build MyRocks or TokuDB at all and all have the following warnings from cmake
   - 20:01:48 -- Not building with TokuDB storage engine, you must specify -DWITH_TOKUDB=1|ON|FORCE to cmake in order to build with TokuDB.
   - 20:01:48 -- Not building with MyRocks storage engine, you must specify -DWITH_ROCKSDB=1|ON|FORCE to cmake in order to build with MyRocks.


-DWITH_TOKUDB=1 -DWITH_ROCKSDB=1
--------------------------------
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/798/ 
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/801/

There was a jenkins/github issues, so needed a matrix reload.

We can see again all platforms pass except for yakkety debug which is due to a compilation issue in MyRocks, logged ans a pretty easy fix:
 - 21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/ha_rocksdb.cc: In member function ‘void myrocks::ha_rocksdb::convert_record_to_storage_format(const rocksdb::Slice&, myrocks::Rdb_string_writer*, rocksdb::Slice*)’:
  - 21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/./././rdb_utils.h:97:48: error: nonnull argument ‘pk_unpack_info’ compared to NULL [-Werror=nonnull-compare]

This is where the changes get more interesting as MyRocks is now compiling and testing where is should, and not where it shouldn't:
 - centos 6 32:
   - 20:03:55 -- Building with MyRocks storage engine = 1
   - 20:03:55 CMake Warning at storage/rocksdb/CMakeLists.txt:22 (MESSAGE):
   - 20:03:55   x86_64 is only platform supported.  i686 found.  Not building MyRocks
 - debian wheezy:
   - 20:04:26 CMake Warning at storage/rocksdb/CMakeLists.txt:29 (MESSAGE):
   - 20:04:26   GCC >= 4.8.0 required.  4.7.2 found.  Not building MyRocks
 - all others build and test with noted exception of yakkety debug
   - 20:01:12 -- Building with MyRocks storage engine = 1
   ...
   - 20:37:36 ==============================================================================
   - 20:37:36 
   - 20:37:36 TEST                                  WORKER RESULT   TIME (ms) or COMMENT
   - 20:37:36 --------------------------------------------------------------------------
   - 20:37:36 
   - 20:37:36 worker[3] Using MTR_BUILD_THREAD 301, with reserved ports 13010..13019
   - 20:37:36 worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
   - 20:37:36 worker[2] Using MTR_BUILD_THREAD 302, with reserved ports 13020..13029
   - 20:37:37 rocksdb.gap_lock_error                   w3 [ pass ]    502
   - 20:37:37 innodb.gap_lock_error                    w1 [ pass ]    488
   - 20:37:37 tokudb.gap_lock_error                    w2 [ pass ]    529
   - 20:37:41 --------------------------------------------------------------------------
   - 20:37:41 The servers were restarted 0 times
   - 20:37:41 Spent 1.519 of 8 seconds executing testcases
   - 20:37:41 
   - 20:37:41 Completed: All 3 tests were successful.



-DWITH_TOKUDB=FORCE -DWITH_ROCKSDB=FORCE
----------------------------------------
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/799/
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/802/

There was a jenkins/github issues, so needed a matrix reload.

In this test, we are forcefully building TokuDB and MyRocks on all platforms, those where they are no supported show as complete cmake/build failures:
 - centos 6 32:
   - 20:07:02 CMake Error at storage/rocksdb/CMakeLists.txt:22 (MESSAGE):
   - 20:07:02   x86_64 is only platform supported.  i686 found.  Not building MyRocks
 - debian wheezy:
   - 20:18:54 CMake Error at storage/rocksdb/CMakeLists.txt:29 (MESSAGE):
   - 20:18:54   GCC >= 4.8.0 required.  4.7.2 found.  Not building MyRocks
 - all others build and test as above still with exception of yakkety debug



Summary:
--------
These changes 'normalize' the cmake checks between MyRocks and TokuDB and with the exception of the yakkety compilation failre, will allow TokuDB and MyRocks to build cleanly on all supported platforms and skip those where they are not supported without needing any external scripting to exclude the platforms. The addition of the FORCE allows release builder scripts to ensure they are built fully on desired platforms or error out at the cmake stage.

**Review by laurynas-biveinis — APPROVED** [review]
Excellent, only red tape needs to be done now:
- this is a change for TokuDB as well, needs something to track (DB or LP blueprint or ...)
- please file a BLD to notify packagers of =FORCE

**Comment by george-lorch** [comment]
Actually, there is a bp for it but I failed to add the link here to the PR : https://blueprints.launchpad.net/percona-server/+spec/myrocks-tokudb-cmake-force

I was planning on a BLD ticket once we passed review and were merging. I didn't want them to run off starting anything based on an interface that doesn't yet exist in the trunk.

**Comment by laurynas-biveinis** [comment]
OK

**Comment by george-lorch** [comment]
https://jira.percona.com/browse/BLD-691

**Pull request merged**
