### PR TITLE
MYR-51 : rocksdb.rocksdb_cf_options missing upstream include file inc…

### PR DESCRIPTION
**Pull request by george-lorch**
…/restart_mysqld_with_options.inc

- Copied in upstream Facebook MySQL include file.

### CODE REVIEW

**Comment by george-lorch** [comment]
This one might need a launchpad blueprint...

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
This is already handled by our restart_mysqld.inc backport that introduced restart_parameters argument.

**Comment by george-lorch** [comment]
OK, changed test case over to using PS restart_myslqd.inc with restart_parameters. Tests out fine. Also audited the test and verified it is good for have_rocksdb without as_default.

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by laurynas-biveinis** [comment]
This is going to need a re-record in 5.7

**Comment by george-lorch** [comment]
It will definitely need re-recorded as part of "5.7 mtr - re-record tests that use restart_mysqld.inc due to new comment in output" and possibly others.

**Pull request merged**
