### PR TITLE
PS-7886 RocksDB server variables missing from documentation (8.0)

### PR DESCRIPTION
**Pull request by patrickbirch**
M source/myrocks/variables.rst

### CODE REVIEW

**Review by mohitj1988 — APPROVED** [review]
LOOK GOOD TO ME

**Comment by inikep** [comment]
`rocksdb_enable_pipelined_write` is `OFF` by default
Sorry it was my mistake.

**Comment by patrickbirch** [comment]
Fixed.

**Review by inikep — APPROVED** [review]
LGTM

**Comment by patrickbirch** [comment]
This pull is closed because the documentation has been moved to another repository.

**Pull request closed without merging**
