### PR TITLE
Fix for DOC-658 mentioning that innodb-force-recovery>0 prevents…

### PR DESCRIPTION
**Pull request by fiowro**
… to modify system tables

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
I am not sure where would be the right place to document this. innodb_corrupt_table_action is not necessarily the one - innodb_corrupt_table_action and innodb_force_recovery are two different things, and the use cases described (MyRocks installation/uninstallation etc.) will not be found through innodb_corrupt_table_action documentation.

IMHO in the present state/scope of our manual it does not really belong here, but a bug should be filed upstream to improve their docs.

**Comment by fiowro** [comment]
I'd say this file is currently the only place in docs mentioning innodb_force_recovery.

**Comment by laurynas-biveinis** [comment]
Yes, but the fact that it's the only place is not sufficient to make it the right place. How would someone trying to install a plugin with innodb_force_recovery consider innodb_corrupt_table_action docs?

**Comment by laurynas-biveinis** [comment]
What's the status of this?

**Pull request closed without merging**
